### ISSUE TITLE
Markdown oddities

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/guides-source#1013]
![image](https://user-images.githubusercontent.com/1372946/63558453-d757b780-c501-11e9-8e0b-a892ccb67f6a.png)

https://guides.emberjs.com/release/accessibility/application-considerations/#toc_ember-applications-vs-roleapplication

(1) Not sure why `Ember applications vs role="application">` appears?
(2) `TL;DR` has dotted underline. On hover, a question mark appears (hard to capture in screenshot)

**Comment by mehulkar** [comment]
Both of those seem expected. 

- The first is the title of the section (maybe it could be changed?)
- The second is using the `<abbr>` tag (which I didn't know about ebfore reading this). In Safari, it doesn't seem to do anything, but https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr

**Comment by amyrlam** [comment]
@mehulkar Appreciate the chime in! 

^ Changed to #s above

//

For (1), the title appears 2x is what I mean, the second time with a trailing `>`:

![image](https://user-images.githubusercontent.com/1372946/63614091-11bf6400-c597-11e9-96b0-02eec761f19c.png)

But the `##` heading only appears 1x in the markup, and doesn't repeat for other instances of `##`:

![image](https://user-images.githubusercontent.com/1372946/63614186-4f23f180-c597-11e9-99c5-2ed47d705894.png)

//

For (2), you are totally right, just checked out the [raw](https://raw.githubusercontent.com/ember-learn/guides-source/master/guides/release/accessibility/application-considerations.md) to see the `<abbr>` tag. So it seems like that is expected...TIL! thank you!

**Comment by MelSumner** [comment]
@mansona can you double check to see if this is something strange in the underlying app? 

I can confirm that the markdown is fine, but it's rendering strangely. 

Markdown:
![image](https://user-images.githubusercontent.com/4587451/64079679-fd264e80-ccaf-11e9-943c-b50f863b1d71.png)

Render:
![image](https://user-images.githubusercontent.com/4587451/64079682-10391e80-ccb0-11e9-9f66-3f1e1da2e9e0.png)

**Comment by llunn** [comment]
This can be fixed by changing the quotes in the heading 3 to double single quotes like it was previously.

If someone doesn't get to it before i get my fork woes resolved I'll put in a PR for it.
