### ISSUE TITLE
Embedding Ember.js

### ISSUE THREAD

**Issue by ryanolsonx** [ember-learn/guides-source#1018]
From an end-user perspective, https://guides.emberjs.com/release/configuring-ember/embedding-applications/ isn't complete.  It tells me how to configure Ember.js so that it _can_ be embedded, but it misses the last step: embedding the Ember.js application.

It would be very helpful to have an example of how to actually embed an Ember.js application after following those steps.

For example, if I have an existing React.js website, do I build the Ember.js application and place the js/CSS files in the project somewhere and reference them in my index.html?  Or do I need to actually import App.js?  I've been struggling to understand what I would do next to embed my Ember.js app.

Thank you!

**Comment by MelSumner** [comment]
I think including it in the official documentation would mean that it's something we encourage- and it's definitely a hack. 

Maybe we can find someone to write a blog post about it, so the resource exists. I'm not sure it's something we want on the guides though.

**Comment by acorncom** [comment]
@ryanolsonx I'd concur with @MelSumner on this one. I've been working on a small book on this topic (and may write some blog posts on it as well) but it's not exactly **fun**, so probably not something we should have in the official guides (which we aim to use for best practices info). If you'd like some pointers, feel free to ping me on the Ember Discord (same username as here on Github) and I can get you going.

**Comment by chancancode** [comment]
@ryanolsonx you should be able to run `ember build` (or `ember build -prod`), take the assets in `/dist` (other than the `index.html`) and include them on your page with `<script>` and `<style>` tags, in the same order that the the built `index.html` have them included (in particular, `vendor.js` first and then `app.js`). Once loaded, the app should boot and attach itself to the specified `rootElement` (which would have to be present on the page by then).
