### ISSUE TITLE
Accessibility section issues

### ISSUE THREAD

**Issue by mehulkar** [ember-learn/guides-source#1019]
New Accessibility section is 🔥! 

Found 3 issues:

- In the [Accessibility Addons section](https://guides.emberjs.com/release/accessibility/application-considerations/#toc_accessibility-addons), the `ember-component-focus` addon is recommended with the note that it provided a Mixin. That might be a little confusing considering that ember is discouraging the use of Mixins going forward.
- The [language attribute section](https://guides.emberjs.com/release/accessibility/application-considerations/#toc_language-attribute) says:

   > If there happens to be any content on the page that is in a different language from that declared in the <html> element, the lang attribute can be used on the parent element to indicate a different language.

    > Note: a page cannot have multiple language attribute values.

    This was confusing since it's both saying that you can have two `lang` attrs on the page, and then says you can't have multiple. Maybe that could be cleared up?

- Zoey's note [here](https://guides.emberjs.com/release/accessibility/application-considerations/#toc_accessibility-addons) is cut off on Mobile (iPhone XS) (I looked around for other Zoey says, and I'm able to view the one [here](https://guides.emberjs.com/release/tutorial/simple-component/) just fine, so it seems isolated.

    ![IMG_1976](https://user-images.githubusercontent.com/490968/63610320-0ddb1400-c58e-11e9-8006-3851ee44e3b9.png)

**Comment by MelSumner** [comment]
> This was confusing since it's both saying that you can have two lang attrs on the page, and then says you can't have multiple. Maybe that could be cleared up?

There can't be multiple values for the lang attribute. 

so this is okay: 
```html 
<html lang="en">
....
  <p> Hello in Spanish is <span lang="es">Hola!</span></p>
...
</html>
```

This is not okay: 
```html
<html lang="en fr">
...
</html>
```

Of course, as I write this, I realize we could add this example to the documentation to clarify. Thank you for the suggestion!!

**Comment by MelSumner** [comment]
I think I have addressed most of these issues. We'll need to look at the mixin again and see what we want to do about it, but that will require some discussion. Thank you for your feedback!
