### ISSUE TITLE
Refactor deploy script to prevent timeout

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1026]
Instead of making Netlify run the build, we should make Travis run the build and push the built files to Netlify. We can delay this for a little while, but not long. Our deployment builds on Netlify seem to be failing at a significant rate, maybe 30-50%. The cause of this is that Netlify appears to have a 15 min time limit that cannot be changed.

This approach may be helpful: https://therocketeers.github.io/blog/using-travis-ci-to-deploy-jekyll-on-netlify/

**Comment by jenweber** [comment]
I emailed Netlify to ask about extending the time limit.

Worst case scenario, I think we could build the app locally and push the dist directory using the CLI. We'll see what they say!

**Comment by jenweber** [comment]
I heard back from Netlify and the only way to get a longer build time is to subscribe to an enterprise plan.

We should run the build on Travis or locally, and then push to Netlify.

**Comment by locks** [comment]
We have worked around this for now with the static content for older versions :)
