### ISSUE TITLE
Searching the v3.2 doc

### ISSUE THREAD

**Issue by dcyriller** [ember-learn/guides-source#104]
It looks like the v3.2 doc hasn't been scrapped by algolia yet (https://github.com/algolia/docsearch). 

Requests to algolia return empty payloads when POST payload includes`facetFilters: [["version:v3.2.0"]]"}`. 

Any thought on how the indexing may be triggered?

**Comment by jenweber** [comment]
Thanks for the note @dcyriller! We are working on getting that fixed.

@sivakumar-kailasam can you close this when the Algolia fix is done? Thank you!

**Comment by dcyriller** [comment]
If I can help, let me know @jenweber

**Comment by sivakumar-kailasam** [comment]
@dcyriller thanks for offering to help. We already have a custom index for the API docs & the current plan is to create new indexes for guides & populate them periodically. 

If you feel up for it please reach out to me on slack & I can provide more information to get you started on this

**Comment by jenweber** [comment]
Closed, our search issues are fixed
