### ISSUE TITLE
Replace references to jsmodules.io with an MDN link

### ISSUE THREAD

**Issue by Phaeilo** [ember-learn/guides-source#1040]
The getting started guide provides an explanation on JavaScript modules. This includes a link to `jsmodules.io`. This website contains some advertising text and no relevant information to JavaScript modules. I think this link should be changed to a more relevant resource, for example MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by sivakumar-kailasam** [comment]
Thanks for bringing this to our attention. We didn't realise that the content on that site changed. 

We'd be happy to accept a PR from anyone with this change.

**Comment by ClaytonTurner** [comment]
I could tackle this

**Comment by sivakumar-kailasam** [comment]
Go for it!

**Comment by rwjblue** [comment]
Closed by https://github.com/ember-learn/guides-source/pull/1041
