### ISSUE TITLE
Non accessible img alt in Services Tutorial

### ISSUE THREAD

**Issue by Alonski** [ember-learn/guides-source#1056]
# Description
The tutorial page for services contains a code example with non accessible use of alt in an img tag.

Here: https://github.com/ember-learn/guides-source/blob/master/guides/release/tutorial/service.md#display-maps-with-a-component
Online: https://guides.emberjs.com/release/tutorial/service/#toc_display-maps-with-a-component

The offending code:
```hbs
    <img src={{this.rental.image}} alt="">
```

**Comment by Alonski** [comment]
cc @MelSumner

**Comment by chiangs** [comment]
Happy to do this quick and easy one :)
