### ISSUE TITLE
Tutorial infra bugs - Fix the /tutorials/ index and infinite +++++

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1069]
Right now if you visit /tutorials/ on the octane guides preview, it goes nowhere. This is a bug.

If you click on a page, it spawns lots of extra +++++ signs.

**Comment by llunn** [comment]
This also affects non-octane.  

The [problem is here](https://github.com/ember-learn/guidemaker-ember-template/blob/9ccf8878b92e660198b9a19fb0aa046b3c0b85f0/app/components/guides-article.js#L110) in guidemaker-ember-template .

**Comment by locks** [comment]
No longer applicable.
