### ISSUE TITLE
Links in headers does not render correctly

### ISSUE THREAD

**Issue by chancancode** [ember-learn/guides-source#1091]
Something like this:

```md
### [Some Title With Link](...)

* some
* content
```

Causes some kind of rendering bug that turns the whole section (the h3 and the entire list) to become a single link.

**Comment by chancancode** [comment]
Workaround atm: https://github.com/ember-learn/super-rentals-tutorial/pull/61

**Comment by MinThaMie** [comment]
I don't think this one is still relevant, so I'll close it
