### ISSUE TITLE
Add ember fetch to the octane upgrade guide

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1107]
When you disable the jquery integration, you have to add ember fetch for ember data to keep working.

I think the intention is to include ember fetch in ember source, but I am not sure if that has been done yet, and for which versions.

**Comment by Charizard** [comment]
@jenweber Seems like ember data automatically falls back to use browsers `fetch` API when disabling jquery integration. But, the caveat being that it would not work in non supported browsers without `ember-fetch` (ahem IE). Ref: https://github.com/emberjs/data/blob/master/packages/adapter/addon/-private/utils/fetch.ts

So, I would suggest we should add this in the [Caveats](https://octane-guides-preview.emberjs.com/release/configuring-ember/optional-features/#toc_caveats) section of removing jquery integration.
