### ISSUE TITLE
Built-in helpers - The let helper - Code/narrative mismatch

### ISSUE THREAD

**Issue by mitchlloyd** [ember-learn/guides-source#1113]
I've been reading through the preview guides and I'm enjoying them!

I noticed that [the section about the let helper](https://octane-guides-preview.emberjs.com/release/templates/built-in-helpers/#toc_the-let-helper) seems to be in flux. It mentions using a `capitalize` helper but that doesn't appear in the example code. Instead the code uses `concat` only.

**Comment by rwjblue** [comment]
Thanks for reading through, and reporting!

**Comment by locks** [comment]
This seems to have been addressed :)
