### ISSUE TITLE
ember serve vs. yarn/npm run start

### ISSUE THREAD

**Issue by samselikoff** [ember-learn/guides-source#1133]
Just a small inconsistency. The quickstart says

```sh
cd ember-quickstart
ember serve
```

but my terminal showed

```
👉   We suggest you that you get started by typing:

$ cd ember-quickstart
$ yarn start
```

Also the language "We suggest you that you get started by typing" has a typo and (I think) could be more direct! Maybe "Get started by typing:"

**Comment by rwjblue** [comment]
Thanks for reporting!

> We suggest you that you get started by typing:

This message is printed by ember-cli itself.

@dcyriller - Have any cycles to poke at this? I think it would also target the `release` branch of ember-cli...

**Comment by dcyriller** [comment]
You're right, "Get started by tying" is better (https://github.com/ember-cli/ember-cli/pull/8882).

That said, can I argue for `yarn start` over `ember serve`? 😉

Running `ember serve` implies ember-cli is installed globally. Instead `yarn start` (or `npm start`) executes ember-cli project's version.

Globally installed packages tend to be outdated very fast. Should we not reference local usage over the global one whenever it is possible?

I have no idea how changes are made to the guides. Should the suggestion to change `ember serve` by `yarn start` be discussed? Or opening a PR for is fine?

Depending on your answers, I'll update my ember-cli PR to change `yarn start` to `ember serve` / open a PR against the guides to make the opposite change.

**Comment by dcyriller** [comment]
Please forget about my previous comment. I won't have time / focus to do what I suggest.

The ember-cli PR is updated with `ember serve`.

**Comment by rwjblue** [comment]
> That said, can I argue for yarn start over ember serve? 😉

Ya, I definitely agree with you here.
