### ISSUE TITLE
Update Octane modifier examples to use `ember-modifier`

### ISSUE THREAD

**Issue by pzuraq** [ember-learn/guides-source#1151]
We recently put together [ember-modifier](https://github.com/ember-modifier/ember-modifier) to provide single community driven modifier API that succeeds both `ember-functional-modifiers` and `ember-class-based-modifiers`. We need to update the existing examples that use the other libraries to use it instead.

Note, the docs shouldn't be too in depth - the addon should still provide the majority of documentation and be considered the canonical source of truth. Existing examples could probably be updated directly without adding any new ones.

**Comment by sivakumar-kailasam** [comment]
Fixed by #1154
