### ISSUE TITLE
Actions change API without a description

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/guides-source#117]
This section https://guides.emberjs.com/release/templates/actions/#toc_modifying-the-actions-first-parameter changes from the element modifier version of actions to the closure version (? - should probably also give a name to the two types so users know what to say/search for) without even a sentence about why, what the difference is, when to use which, and the caveats. This makes actions quite confusing for people just starting with the framework.

**Comment by Gaurav0** [comment]
I'm not seeing the issue. @knownasilya Can you explain?

**Comment by knownasilya** [comment]
The linked section is the place were it changes. Scrolling back up shows the element modifier version

**Comment by jelhan** [comment]
The guides should only use closure actions in my opinion. Element modifier version of actions are a footgun and way more complex to understand for newcomers. I wondered that they are still the preferred way actions are teached by guides. Was there already a discussion / decision about changing that?

**Comment by jenweber** [comment]
This will be addressed with the upcoming Octane release, where we have better clarity around actions. See https://github.com/ember-learn/guides-source/blob/octane/guides/release/components/actions-and-events.md

Thanks all for your help!
