### ISSUE TITLE
Page in older versions appears to exist on release, when it actually does not exist on release

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/guides-source#1179]
See: https://github.com/ember-learn/guides-source/pull/1171

* If you go from the v1.10.0 link https://guides.emberjs.com/v1.10.0/models/the-rest-adapter/, then click "View v3.13.0", the url https://guides.emberjs.com/release/models/the-rest-adapter/ "falsely" exists
* When you go directly to https://guides.emberjs.com/release/models/the-rest-adapter/, it does not exist. 

cc @thejonrichmond

**Comment by jenweber** [comment]
Thanks for reporting!

Likely this is continued problems with a refactor that used findAll instead of query. A PR here partially reverted the buggy behavior: https://github.com/empress/guidemaker/pull/26

I think we need to turn the rest of the findAlls into queries.

**Comment by jenweber** [comment]
Open PR to fix this: https://github.com/empress/guidemaker/pull/30
