### ISSUE TITLE
[Octane] Helper function write up for let seems incomplete?

### ISSUE THREAD

**Issue by acorncom** [ember-learn/guides-source#1206]
Reading over the [helper functions page](https://octane-guides-preview.emberjs.com/release/components/helper-functions/) (toward the bottom), the `let` section seems to intend to introduce a `(capitalize)` helper and use it for `firstName` and `lastName`. But I'm a bit puzzled about **how** we intended to use it (otherwise I'd just send in a PR).

@pzuraq any pointers here?

**Comment by acorncom** [comment]
This also is apparently a duplicate of https://github.com/ember-learn/guides-source/issues/1113

**Comment by pzuraq** [comment]
Hmm, yeah I’m unsure what happened there, on my last pass I just copy/pasted what we had in the previous revision. We can probably just make the example consistent with capitalize everywhere

**Comment by locks** [comment]
Closing since it's a duplicate as mentioned above!
