### ISSUE TITLE
[Octane] Nested components discussion / code block a bit unclear

### ISSUE THREAD

**Issue by acorncom** [ember-learn/guides-source#1207]
Reading through the [nesting components](https://octane-guides-preview.emberjs.com/release/components/introducing-components/#toc_nesting-components-in-folders) section, things were reading well.

But then I hit the final code block section:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/802505/70594157-d9bb4b80-1b9c-11ea-9c67-0b05b9202110.png">

Although I understand what is going on in the paragraph above it, I'm having a hard time understanding how the file tree (and it's additions/subtractions) correlates to the thing we're working to teach in that section. Should we just remove the code snippet completely?

@pzuraq looks like you were the last one to touch this section, any pointers here?

**Comment by pzuraq** [comment]
it looks like the additions and subtractions are off by one line, it should be adding index files and removing top level files. We can also probably add more language to the preceding paragraph to tell the user what’s about to happen:

“For instance, we could move the `received-message.hbs` component to `received-message/index.hbs`, and still use it as `<ReceivedMessage/>`
