### ISSUE TITLE
Octane guides don't mention template `else if`/`else`

### ISSUE THREAD

**Issue by CodingItWrong** [ember-learn/guides-source#1237]
Before Octane the Ember Guides referenced `{{#if}}`, `{{else if}}`, and `{{else}}` on the "Conditionals" page: https://guides.emberjs.com/v3.14.0/templates/conditionals/

As of the Octane Guides, the Conditional Content page only mentions `{{#if}}` — and `{{else if}}` and `{{else}}` are missing. I wasn't able to find the latter referenced anywhere in the guides.

I think it would be difficult for most Ember users who don't already know about `{{else if}}` and `{{else}}` to find out about them without them being on this guide page—I think they should be added back into the new form of the page.

**Comment by chancancode** [comment]
Sounds good to me, I think we can add something back

**Comment by ijlee2** [comment]
I'll make an update to https://guides.emberjs.com/release/components/conditional-content/ and backport the update all the way to 3.15.
