### ISSUE TITLE
Align Upgrade Guide with the Octane release blog post

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1239]
The advice given on this page https://guides.emberjs.com/release/upgrading/current-edition/ should be in harmony with https://blog.emberjs.com/2019/12/20/ember-3-15-released.html and https://blog.emberjs.com/2019/12/20/octane-is-here.html

To do:
- [x] add documentation and links about octanify
- [x] make sure option flag lists are complete
- [x] any other things that need to be added in

**Comment by locks** [comment]
Work accomplished x)
