### ISSUE TITLE
Fix broken link in the upgrade guides

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1252]
On https://guides.emberjs.com/release/upgrading/current-edition/#toc_implementing, step 5 has a bad link. To close this issue, figure out what it should be linking to and fix the link. Thanks!

**Comment by conormag** [comment]
@jenweber the broken link is `https://guides.emberjs.com/release/upgrading/current-edition/editions/` and its link text is the bold in 
"Try refactoring one existing component to use Octane style. Check out the Cheat Sheet and **Editions Deep Dive** for some pointers."

I think the text should read:

"Try refactoring one existing component to use Octane style. Check out the Cheat Sheet and [In-depth Topics](https://guides.emberjs.com/release/in-depth-topics/) for some pointers."

I can submit a PR if this is correct?

**Comment by Aswathprabhu** [comment]
Working on it...
