### ISSUE TITLE
Slow load of pages

### ISSUE THREAD

**Issue by sharath-sriram** [ember-learn/guides-source#1255]
Every webpage in the Ember.js guides (https://guides.emberjs.com/release/) takes a considerable amount of time to load after the user's click.

There is also no user feedback to show that the click request has been registered, making the user confused if the button is actually working. There is a need to speed up the page load / at least show some kind of feedback to the user to let him know that the page is loading.

**Comment by amyrlam** [comment]
I'm having the same issue. And I can help with this!  

Could we add a loading state?

![guides-slow](https://user-images.githubusercontent.com/1372946/73098857-1918cf80-3e9f-11ea-948c-c61ab439c3a7.gif)

**Comment by sharath-sriram** [comment]
Yes, a loading state would help greatly.

**Comment by sharath-sriram** [comment]
Also, Issue #1266 seems similar to this ? Should we close one of the issues and proceed further with another ?

**Comment by locks** [comment]
Yes, thank you :) Tracked in https://github.com/ember-learn/guides-source/issues/1266 !
