### ISSUE TITLE
Broken link in Refactoring Checklist

### ISSUE THREAD

**Issue by jrock2004** [ember-learn/guides-source#1258]
There is a link that is broken when you are looking at https://guides.emberjs.com/release/upgrading/current-edition/#toc_refactoring-checklist

Step 3 which is Use Named Arguments link is broken. Currently is links to https://guides.emberjs.com/release/upgrading/current-edition/editions/#toc_named-arguments

It looks like it should be https://guides.emberjs.com/release/upgrading/current-edition/templates/#toc_named-arguments

**Comment by jamescdavis** [comment]
This was fixed by #1258. @jenweber
