### ISSUE TITLE
typo in release/upgrading/current-edition/action-on-and-fn.md

### ISSUE THREAD

**Issue by conormag** [ember-learn/guides-source#1259]
In [https://guides.emberjs.com/release/upgrading/current-edition/action-on-and-fn/#toc_the-action-decorator](https://guides.emberjs.com/release/upgrading/current-edition/action-on-and-fn/#toc_the-action-decorator)

we read: 

> In Ember Octane, **components** are no longer defined on the actions object of a component or controller. Instead, they are standard class methods decorated with the @action decorator.

`components` should be replaced with `actions` or `action functions`?

**Comment by rwjblue** [comment]
I'd say we should update to:

```
In Ember Octane, actions are no longer defined on the actions object of a component or controller. Instead, they are standard class methods decorated with the @action decorator.
```

Would you mind sending in a pull request for this?

**Comment by conormag** [comment]
will do
