### ISSUE TITLE
Improve contributing page in guides

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#1285]
I think we should ultimately redirect to help-wanted.emberjs.com or similar, but for now we should at least:

- [ ] Update the link to "Ember Website"
- [ ] Update the links to "Ember Guides"
- Review "Libraries Used By Ember" (this one is a bit more fuzzy)
  - [ ] Remove morph-range
  - [ ] Update "Glimmer 2" and "HTMLBars"
- [ ] Link to help-wanted.emberjs.com
- [ ] Link to community page (so people can contribute via support, etc)
- [ ] Add some prose about kinds of contribution other than code

**Comment by efx** [comment]
I think mention of https://github.com/adopted-ember-addons/ would be great too.

**Comment by rajasegar** [comment]
@locks I would like to take a look at this, can you please assign it to me?

**Comment by rajasegar** [comment]
@locks For the prose about kinds of contribution other than code, I have copied the opening paragraph from Jessica's answer to Readers question on discuss.emberjs.com
https://discuss.emberjs.com/t/readers-questions-id-like-to-contribute-to-ember-how-can-i-get-started/14915
Is it OK?
