### ISSUE TITLE
Event types are supported (camelCase)

### ISSUE THREAD

**Issue by broerse** [ember-learn/guides-source#1310]
On Ember 3.16 `key-down` does not work but `keyDown` does https://guides.emberjs.com/release/components/built-in-components/#toc_actions 

I am not sure if the guides are wrong or this a bug.

@jenweber if it is not a guides thing I will file a bug report

**Comment by locks** [comment]
Thanks for reporting, being tracked at https://github.com/ember-learn/guides-source/issues/1310.
