### ISSUE TITLE
further modernize core-concepts.svg

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#1311]
Continue the great work in https://github.com/ember-learn/guides-source/pull/631.

The [core concepts.svg](https://github.com/ember-learn/guides-source/blob/0cdd97b6518d42c7e6b04a4f8d38c7fbbeaa09de/public/images/ember-core-concepts/ember-core-concepts.svg) file has some snippets that need updating:
<img width="733" alt="Screen Shot 2020-02-19 at 15 25 48" src="https://user-images.githubusercontent.com/472721/74872904-23a67780-532c-11ea-905b-b55a9db35b75.png">

- `this.model` should be `@model`
- The route example should use native classes

**Comment by rajasegar** [comment]
@locks I can pick this up, can you please assign it to me?

**Comment by rajasegar** [comment]
The new file will look like this:
![Screenshot_2020-03-29 Anatomy of an Ember App - Getting Started - Ember Guides](https://user-images.githubusercontent.com/2083049/77840018-52700300-71a0-11ea-9517-832a68639588.png)

**Comment by rajasegar** [comment]
This can be closed as the PR is already merged
https://github.com/ember-learn/guides-source/pull/1393
