### ISSUE TITLE
Guides should recommend custom inflector rules be put in initializers instead of models

### ISSUE THREAD

**Issue by loren-osborn** [ember-learn/guides-source#132]
The official ember docs [currently recommend](https://guides.emberjs.com/release/models/customizing-adapters/#toc_pluralization-customization) custom inflector rules be added to app/models, which seems like an odd place and can introduce bugs if the inflector rules are not properly loaded before a user interacts with the store.  I consulted with @runspired, and we agreed that a better place for such global setup to live would be in `app/initializers`.

**Comment by acorncom** [comment]
hey @loren-osborn that sounds like a great idea, would you have time to send in a PR to update things? The guides are a community resource, so we actively encourage folks to send in PRs to make the changes they're noticing a need for 😄

**Comment by loren-osborn** [comment]
@acorncom, I would love to but don’t have the bandwidth to get to this in the foreseeable future. I’m sorry I can’t contribute more at this time.

**Comment by MonsieurDart** [comment]
Hey, I've tested this and created a PR to the docs:

https://github.com/ember-learn/guides-source/pull/560

Is this well what you recommend, @loren-osborn?

Thanks for your help.
