### ISSUE TITLE
Add deployment to the quick start

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1320]
Part of what makes web apps awesome is the ability to see them live on the web. We should add a brief deployment section to the quickstart. This is a followup from a conversation with @wycats.

## Structure:

This section will describe 2 paths, in order to better serve the range of devs who might try Ember. It will describe deploying to one provider but also list others that you can deploy to and link to their resources.

Path A
- Push code to GitHub using command line
- Tell Netlify to deploy it

Path B
- Drag and drop files into Netlify

## Why Netlify?

- Lowest level of knowledge needed to get a site live
- Free, no credit card required
- Long-term supporter of Ember :heart:
- I got my own site up in 5 mins the other night

**Comment by locks** [comment]
PR has been merged.
