### ISSUE TITLE
Possible typo within the in-depth section of the guides

### ISSUE THREAD

**Issue by leondmello** [ember-learn/guides-source#1349]
I'm a little confused on [this part of the documentation](https://github.com/ember-learn/guides-source/blob/master/guides/v3.16.0/in-depth-topics/patterns-for-actions.md#destructuring-objects-passed-as-action-arguments)
```js
export default class UserProfileComponent extends Component {
  @service login;

  @action
  async deleteAccount() {
    await this.login.deleteUser();

    this.args.didDelete(this.login.currentUserObj);
  }
}
```
The template doesn't reference `currentUserObj`, 
```hbs
<UserProfile @didDelete={{fn this.userDeleted this.login.currentUser.id}}
```
It seems the second part is just directly accessing the service and not really using the passed in argument from the call `this.args.didDelete(`

**Comment by locks** [comment]
Thanks for reporting. Are you able to send a PR with a fix
