### ISSUE TITLE
Quest: Transition guides documentation to use angle bracket invocation (rfc 311)

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/guides-source#139]
See [RFC 311](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md)

This is a placeholder for a quest issue for converting the guides to introduce and explain angle bracket component invocation to ember developers.

**Comment by jenweber** [comment]
I think the decision was maybe we wait for Octane before documenting this? Just wanted to add a note that contributors should not attempt this yet. Thoughts?

**Comment by jenweber** [comment]
We are now moving forward with this.

To-do:
- [ ] convert to Angle Brackets in code blocks https://github.com/ember-learn/guides-source/pull/357
    - [ ] opened PR
    - [ ] merged
- [ ] convert Super Rentals to angle brackets https://github.com/ember-learn/super-rentals/pull/115
    - [ ] opened PR
    - [ ] merged
- [ ] Add explanation of Angle Brackets somewhere
    - [ ] figure out where
    - [ ] opened PR
    - [ ] merged

**Comment by MelSumner** [comment]
Does this make #250 a duplicate?

**Comment by mansona** [comment]
does https://github.com/emberjs/ember.js/pull/17554 complete the API docs aspect of this issue? or is there anything special that we need to do?

**Comment by jenweber** [comment]
I think it does complete it. Thanks all for the help!!! Closed 🎉
