### ISSUE TITLE
Remove "Ember Octane is Here" banner

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#1398]
This banner should be removed six months from the publish date of https://blog.emberjs.com/2019/12/20/octane-is-here.html, making that June 20th.

**Comment by jenweber** [comment]
For whoever wants to work on this ticket, you can find where the banner is specified by searching this repo for "Ember Octane is here!" and remove that line.

**Comment by vvkpd** [comment]
I would like work on this card, could you please assign to me?
Thanks

**Comment by ijlee2** [comment]
@vvkpd Thanks for helping out with the Ember Guides! If you have questions, feel free to reach out by commenting in this issue, or joining the `#hacktoberfest` channel at [Ember Discord](https://discord.gg/emberjs).
