### ISSUE TITLE
Doc for updating list is somewhat misleading.

### ISSUE THREAD

**Issue by Aswathprabhu** [ember-learn/guides-source#1405]
https://guides.emberjs.com/release/components/looping-through-lists/#toc_updating-lists

<img width="770" alt="image" src="https://user-images.githubusercontent.com/25875367/80015873-fe7ee280-84ef-11ea-9c4d-08393c65f428.png">

By default, Ember.js will extend the prototypes of native JavaScript objects, right?

So one does not need to convert the messages array to Ember Array here unless they override the EmberENV EXTEND_PROTOTYPES to `false` which is `true` by default.

It can be misleading for newbies, they may come to the conclusion that by default for array mutation to be reactive one must convert them to EmberArray.

**Comment by locks** [comment]
This section has since been updated to tracked properties!
