### ISSUE TITLE
Update screenshots for Ember Inspector section

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#1406]
**NOTICE** https://github.com/emberjs/ember-inspector is releasing v4.0.0 soon, so any that should be the baseline for this work, and not the currently published version (v3.13.2 on my Firefox browser).

At the moment, some of the screenshots in the Ember Inspector chapter of the guides are out of date. For example, the screenshots at https://guides.emberjs.com/v3.17.0/ember-inspector/component-tree/ still show the "View Tree" panel, which I believe has been removed for some time now. And, of course, https://guides.emberjs.com/v3.17.0/ember-inspector/view-tree/ should be removed.

The first phase of the work is to identify which screenshots are out of date so they can be replicated. For now I would not change the introduction page. Part of this work is also confirm which versions of ember.js make Ember Inspector show the "View Tree" or not, so we can backport the updated screenshots to the Guides for that version.

Once we have agreed on the work identified in the previous phase, we move to the second phase where we create issues to address said work.

**Comment by locks** [comment]
Assigned to @rajasegar.

**Comment by rajasegar** [comment]
Screenshots need to be replaced
## Component Tree page
- Component Tree
- Filtering Components ( Angle bracket syntax)
- Hovering over the component tree ( Angle bracket syntax and View in Elements Panel button)
## View Tree page
- Lot of images need to replaced here. I am wondering this page still make sense in the latest version post Octane
## Inspecting Routes page
- Routes panel
- Viewing the Current Route only
## Data Tab
- Inspecting Records
## Tackling Deprecations
- Deprecations Tab
- Filtering and Clearing
## Library info page
- Info tab ( Side panel of What's new is missing)
## Debugging Promises
- Promises Tab

**Comment by locks** [comment]
The View Tree panel is no longer shown for certain versions of Ember applications, so we might need to remove it and redirect to the Components panel.
I would ask someone from the Inspector team (@rwwagner90) which versions of Ember are served different inspectors. I believe we will need at least two different versions of the images if we want the guides to be historically accurate.

**Comment by rwwagner90** [comment]
There are three versions of Inspector. I believe anything before 2.8 is one, then 2.8-3.4 or so is one, and 3.4+ is the only one actively developed. I’m not sure we need to screenshot anything other than latest, so we?

**Comment by locks** [comment]
We already have "old" screenshots, so it's more a matter of keeping them and making sure we backport the new screenshots to the relevant versions, since it should be mostly updating image paths (and redirecting the View Tree panel to the Component panel guide?)

**Comment by rwwagner90** [comment]
@locks I believe everything should be updated now, so screenshots can be taken at any time.
