### ISSUE TITLE
Create a Staging App Demo for Testing the Website Redesign

### ISSUE THREAD

**Issue by jayjayjpg** [ember-learn/guides-source#1408]
Part of https://github.com/ember-learn/ember-styleguide/issues/313

**Comment by mansona** [comment]
There are already demo apps for the template https://github.com/ember-learn/guidemaker-ember-template/pull/30 and how that template applies to this project: https://github.com/ember-learn/guides-source/pull/1265 🎉 (see the netlify preview links at the bottom of the PR)
