### ISSUE TITLE
guides still mention `defaultSerializer` but it's deprecated

### ISSUE THREAD

**Issue by sdhull** [ember-learn/guides-source#1411]
The guides mention [`defaultSerializer` here](https://guides.emberjs.com/release/models/customizing-adapters/#toc_authoring-adapters) but it's been [deprecated](https://deprecations.emberjs.com/ember-data/v3.x/#toc_ember-data:default-serializers).

I'm not sure how to update this section of the guide to remove the mention of `defaultSerializer`. I guess if you're authoring adapters, you need to include instructions for setting up appropriate, corresponding serializers as well.

**Comment by rwjblue** [comment]
Good catch. We should definitely remove the deprecated reference.
