### ISSUE TITLE
Make sure all button elements have an explicit type

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#1416]
By default, ember-template-lint will emit a linting error if a button element in a template does not have an explicit type. That means this would fail linting:

```handlebars
<button>
```

But this would not:

```handlebars
<button type="button">
```

We need to make sure to add an explicit type attribute to all button elements so that any user copying it into their app does not fail linting.
Make sure that the example is not showing a linting error on purpose, and that the button type is correct for the example (e.g. it might be `submit` if it's the submit button of a form).

This work should be done for the [**release**](https://github.com/ember-learn/guides-source/tree/master/guides/release) content.

**Comment by locks** [comment]
Assigned to @roderickdevelopers.

**Comment by roderickdevelopers** [comment]
Just an update on the linting error for button type=""
I started with 3.17 and worked my way back. 
Hopefully this helps a little bit

Ember Cli 3.17 Gives the lint error as expected 
![Ember-cli-3 17](https://user-images.githubusercontent.com/8920079/81091690-935ce500-8ecd-11ea-8037-45c03bdc639f.png)

Ember Cli 3.16 Gives the lint error as expected
![ember-cli-3 16](https://user-images.githubusercontent.com/8920079/81091733-9f48a700-8ecd-11ea-9050-93dff4938a83.png)

Ember Cli 3.15 Gives the lint error as expected
![Ember-cli-3 15](https://user-images.githubusercontent.com/8920079/81091762-a96aa580-8ecd-11ea-9533-89986b65d943.png)

Ember Cli 3.14 Does not give the lint error as expected
![Ember-cli-3 14](https://user-images.githubusercontent.com/8920079/81091793-b2f40d80-8ecd-11ea-91e0-3e3ce5695348.png)

**Comment by ijlee2** [comment]
@locks I checked today that in the `guides/release` folder, all buttons have a type. I think we can close this issue now. Thanks again, @roderickdevelopers!

Resolved in:

- #1425 
- #1431 
- #1433

**Comment by roderickdevelopers** [comment]
No problem!! Glad I could help
