### ISSUE TITLE
Problems running Guides locally - infinite rerenders for locks

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1441]
@locks is this still a problem for you? We updated a bunch of deps and hopefully it's fixed now!

**Comment by locks** [comment]
I installed watchman to get around the project if I remember correctly, I'll check it again1

**Comment by locks** [comment]
Just reproduced it and it's a problem.

**Comment by locks** [comment]
I am getting a screenful of these errors:

```
2020-07-09 10:35 ember[2599] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
```

**Comment by mansona** [comment]
@locks that looks like you have an issue with your Node install 🤔  maybe the version of FSStream (or is FSEvents) might have a binary incompatibility and might need to be re-installed. 

Are you doing something funny with your Node/npm setup?

**Comment by locks** [comment]
@mansona not that I know of! It's a plain of volta install of node@10 that is specified on package.json.

**Comment by mansona** [comment]
so I would say that using volta is doing something funny with your node setup 😂 

Are you able to double check this with system installed Node? or maybe re-install your Node because it sounds like you have issues on your side 🤔

**Comment by locks** [comment]
I have reinstalled Node and the problem persists. I have also not problems with other projects 🤔

> Are you able to double check this with system installed Node?
I am not.

**Comment by mansona** [comment]
do we know anyone else that's using Volta? so we can check if this is a Volta issue? 🤔

**Comment by locks** [comment]
@knownasilya or @NullVoxPopuli maybe?

**Comment by knownasilya** [comment]
🖐️ what do you want tested?

**Comment by mansona** [comment]
@knownasilya from the sounds of it you just need to run the app using Volta 🤷

**Comment by knownasilya** [comment]
So this error if not using watchman https://github.com/ember-learn/guides-source/issues/1441#issuecomment-656023315?

**Comment by knownasilya** [comment]
I get:

```

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: EMFILE
  - codeFrame: [undefined]
  - errorMessage: EMFILE: too many open files, watch
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [null]
    - line: [undefined]
  - message: EMFILE: too many open files, watch
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
```

node 10.16.3
volta 0.7.2

**Comment by knownasilya** [comment]
With watchman 4.9.0 it works but takes 86470ms
