### ISSUE TITLE
Remove references to log bindings and observersFor

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1443]
In https://guides.emberjs.com/v3.12.0/configuring-ember/debugging/#toc_observers--binding, we talk about a feature that appears to have been removed in 3.1.

To close this ticket, remove the incorrect information from Guides versions 3.1 up to the present (aka the release folder).

See https://github.com/emberjs/ember.js/issues/18929 for context before you start. Thanks!

**Comment by ijlee2** [comment]
I can work this today.
