### ISSUE TITLE
Syntax error in Customizing Adapters guide

### ISSUE THREAD

**Issue by gabrieltanchen** [ember-learn/guides-source#1444]
On [this page](https://guides.emberjs.com/release/models/customizing-adapters/), there's the following code:
``` javascript
import JSONAPIAdapter from '@ember-data/adapter/json-api';
import { tracked } from '@glimmer/tracking';
import { inject as service } from '@ember/service';

export default class ApplicationAdapter extends JSONAPIAdapter {
  @service session;
  @tracked session.authToken;
  get headers() {
    return {
      'API_KEY': this.session.authToken,
      'ANOTHER_HEADER': 'Some header value'
    };
  }
}
```

I don't believe `@tracked session.authToken` is valid, and I got a syntax error when trying to implement this. I managed to achieve this with the following:
``` javascript
import Service from '@ember/service';
import { tracked } from '@glimmer/tracking';

export default class SessionService extends Service {
  @tracked authToken;
}
```
``` javascript
import JSONAPIAdapter from '@ember-data/adapter/json-api';
import { inject as service } from '@ember/service';

export default class ApplicationAdapter extends JSONAPIAdapter {
  @service session;

  get headers() {
    return {
      'API_KEY': this.session.authToken,
    };
  }
}
```

I can make a PR to update this page, but I just wanted to check that I'm not missing anything here in case `@tracked session.authToken` actually is valid.

**Comment by ijlee2** [comment]
@gabrieltanchen Apologies for a late reply. I looked at the [Headers customization](https://guides.emberjs.com/release/models/customizing-adapters/#toc_headers-customization) subsection to get more context.

I think you are right that the code should not be showing `@tracked session.authToken`. It seemed to me that, when we had updated `headers` from being a computed property to a getter in `v3.15`, we didn't account for `authToken` correctly.

For your PR, may I suggest the following changes:

1\. Update the text that precedes the code to:

> You can combine tracked properties with ES6 getters to make `headers` dynamic. For example, you may have a `session` service with a tracked property called `authToken`:

2\. For the code, let's remove the line that showed `@tracked session.authToken;`.

```javascript
import JSONAPIAdapter from '@ember-data/adapter/json-api';
import { tracked } from '@glimmer/tracking';
import { inject as service } from '@ember/service';

export default class ApplicationAdapter extends JSONAPIAdapter {
  @service session;

  get headers() {
    return {
      'API_KEY': this.session.authToken,
      'ANOTHER_HEADER': 'Some header value'
    };
  }
}
```

3. Make these changes to the following files:

- `guides/v3.15.0/models/customizing-adapters.md`
- `guides/v3.16.0/models/customizing-adapters.md`
- `guides/v3.17.0/models/customizing-adapters.md`
- `guides/release/models/customizing-adapters.md`

(assuming the current release is still 3.18)

Please let us know that you saw this message and whether you can still work on making a PR. I hope that you're doing well and appreciate your reporting this issue!

**Comment by gabrieltanchen** [comment]
@ijlee2 Thanks for getting back to me! I can certainly make these changes. I'll have some time later this week and will create a PR then.

**Comment by ijlee2** [comment]
Thank you!
