### ISSUE TITLE
Probably error in tutorial, Part 2, Section "Route Params"

### ISSUE THREAD

**Issue by kisumoto** [ember-learn/guides-source#1450]
I'm following that tutorial. My env:
```
ember-cli: 3.18.0
node: 12.18.0
os: linux x64
```
Tutorial link: https://guides.emberjs.com/release/tutorial/part-2/route-params/
Version selected: 3.18.

Tutorial recommends to add test:
```
    assert.dom('article h3 a').hasAttribute('href', '/rentals/grand-old-mansion');
```

but that test doesn't pass even after routing is enabled. Here is what I've got to pass:
```
    assert.dom('article h3 a').hasAttribute('href', '/rental/grand-old-mansion');
```
Difference in rentalS => rental in URL.

**Comment by kisumoto** [comment]
Similar error on the same page:
```
    assert.equal(currentURL(), '/rentals/grand-old-mansion');
```
Again here works test with rental instead of rentalS

**Comment by chancancode** [comment]
Perhaps you defined the route with the singular name in app/routes.js? Nothing wrong with that, the name is not special, they just have to match as you have discovered. The code in the tutorial is automatically executed and tested daily, so I am pretty sure the tests do pass as written.

**Comment by kisumoto** [comment]
Indeed :) Magic Ember! Everything worked like a charm: component loading, LinkTo links, and everything else, except tests where I except /rentals/. Thank you.

**Comment by kisumoto** [comment]
I finished the tutorial, both parts. It works fine. Probably only one minor issue is in this promise:
https://guides.emberjs.com/release/tutorial/part-2/service-injection/

> Feel free to try sending the tweet! However, keep in mind that your followers cannot access your local server at http://localhost:4200/. Don't worry though, **at the end of the tutorial, we will deploy the app to the Internet** so you can show everyone what you made!

Tutorial doesn't teach this thing :)

**Comment by amyrlam** [comment]
@kisumoto thank you, I filed an issue for that: https://github.com/ember-learn/guides-source/issues/1454

If you happen to be interested in making the change (no worries if not!), please comment on the issue!

**Comment by roderickdevelopers** [comment]
I will look into it and take care of this issue this week!

**Comment by chancancode** [comment]
@amyrlam @roderickdevelopers thanks for picking it up, as a reminder the PR should be sent to https://github.com/ember-learn/super-rentals-tutorial. We do intend to cover it (tracked in https://github.com/ember-learn/super-rentals-tutorial/issues/137), just haven't had a chance to do it yet.
