### ISSUE TITLE
Dependency Injection still uses old syntax

### ISSUE THREAD

**Issue by Benjy1979** [ember-learn/guides-source#1473]
In the guides at:
https://guides.emberjs.com/release/applications/dependency-injection/

It is not exemplifying how to inject a service or a controller into a class in the sample app/components/cart-contents.js.  It is using the old syntax only and if it is not supported with classes then it is not stating it so.

**Comment by locks** [comment]
For anyone also stumbling on this issue, you can see an example of service injection at https://guides.emberjs.com/release/tutorial/part-2/service-injection/

**Comment by Benjy1979** [comment]
This issue is about controller injection

**Comment by locks** [comment]
Hm, controllers can only be injected into other controllers and it is not recommended because of the downsides of doing it. The fact that controllers are singletons and the model property is managed by route hooks can trip up people.

**Comment by locks** [comment]
https://api.emberjs.com/ember/3.19/functions/@ember%2Fcontroller/inject

> Creates a property that lazily looks up another controller in the container. Can only be used when defining another controller.

**Comment by Benjy1979** [comment]
I think accessing the parent controller is reasonable..what if you want the query params? Or is there another route that is better to take

**Comment by maxwondercorn** [comment]
@locks I'm working on a PR to update the service examples cited here. I assume I should backport back to 3.15?  

Also, I believe the component classes should be converted native classes and possible glimmer components to be consistent with the rest of the guides.
