### ISSUE TITLE
Document in-element in the Guides

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#1492]
Ember 3.20 includes `in-element` out of the box, which permits developers to render content into an HTML element outside of the hierarchy it would be normally rendered in.
While this feature is documented in API docs, we should investigate if and where it makes sense to mention and use it in the Guides.

**Comment by fozy81** [comment]
Some notes:

A little background in the  [ in-element RFC](https://github.com/emberjs/rfcs/blob/5667872d8cb7df50b48df7fd05fdb77f43f4e024/text/0000-promote-in-element-to-public-api.md) and the [API guidance](https://api.emberjs.com/ember/release/classes/Ember.Templates.helpers/methods/in-element?anchor=in-element) for reference.

There's a couple of addons which previously provided this type of functionality, [ember-wormhole](https://github.com/yapplabs/ember-wormhole) or [ember-elsewhere](https://github.com/ef4/ember-elsewhere). Could be nice to offer similar interactive examples in the guides? 






.

**Comment by faith-or** [comment]
Hi! @locks / @fozy81 -- I would like to try to take this up.

**Comment by fozy81** [comment]
@faith-or Thanks for helping out. I think it's safe to start and someone from the docs team will assign you. I'm a newbie around here 🙂.
