### ISSUE TITLE
Can only run search index using Node 10

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1498]
When I was using Node 12, I was not able to run `ember deploy production` or the release script due to 

```
- build failed
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/jweber/projects/guides-source/node_modules/guidemaker/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
```

This resolved when I switched to Node 10.

**Comment by locks** [comment]
For what is worth, I had a similar problem with `ember deploy` and pinned the versions using Volta https://github.com/ember-learn/guides-source/blob/master/package.json#L107-L110.

**Comment by rwjblue** [comment]
Seems like https://github.com/ember-cli/ember-cli/issues/9235#issuecomment-637697483 should fix.
```

**Comment by rwjblue** [comment]
I think https://github.com/ef4/ember-auto-import/pull/289 is also related.
