### ISSUE TITLE
remove application wrapper in A11y section of the guides

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#1515]
https://guides.emberjs.com/release/accessibility/application-considerations/#toc_application-template-wrapper 

This doesn't need to be here for current releases, since it's not something that we have to turn on anymore.

**Comment by fozy81** [comment]
Hi @MelSumner I've taken a shot at this - see PR. I've removed the following sections/headings as these seem all related to the application wrapper:

    Configuration (heading)
    Application template wrapper (section)
    Ember applications vs role=''application'' (section)

Let me know if that looks okay or if I should change anything etc.

The page now looks like this:

> 
![image](https://user-images.githubusercontent.com/2878163/93806571-3c1f9d00-fc41-11ea-851d-31bf22048631.png)

**Comment by ijlee2** [comment]
Issue has been completed in #1536.
