### ISSUE TITLE
Adapter Documentation is missing 5th parameter

### ISSUE THREAD

**Issue by Benjy1979** [ember-learn/guides-source#1538]
For query() and queryRecord() there is a fifth parameter (adapterOptions) that are not conveyed by the documentation.

https://api.emberjs.com/ember-data/3.21/classes/Adapter/methods/queryRecord?anchor=query

**Comment by ijlee2** [comment]
Hi, @Benjy1979. Thanks for reporting the issue. From [ember-data tests](https://github.com/emberjs/data/blob/master/packages/-ember-data/tests/integration/adapter/store-adapter-test.js#L1532-L1536), I think that the 5th parameter is an `options` hash that can include `adapterOptions`.

It seemed like starting v2.x, possibly earlier, the 5th parameter hadn't been documented. I don't have the historical context to explain why, though.

Let me transfer this issue to `ember-data` repo. I believe a change in code comments there will eventually result in the change in the API documentation. In addition, I think the `ember-data` maintainers will be able to better access what's going on and advise how you may be able to help.

**Comment by ijlee2** [comment]
Actually, it seems I can't transfer an issue from one GitHub organization to another. Let me close this issue and ask you to recreate it in https://github.com/emberjs/data/issues? I will link this issue at `#dev-ember-data` channel on Discord.
