### ISSUE TITLE
Clicking a permalink adds code-diff annotations (plusses and minuses)

### ISSUE THREAD

**Issue by jeffdaley** [ember-learn/guides-source#1548]
![CleanShot 2020-09-30 at 12 27 15](https://user-images.githubusercontent.com/754957/94713075-554adc80-0318-11eb-820d-1ee658302019.gif)

This happens the second time a permalink is clicked on the page.

In the example, I'm clicking the same permalink multiple times (unlikely). But this can also be reproduced by clicking the permalink of different sections (more likely). 

These diff annotations are also selectable, which means the plusses appear in your code when you paste them.

**Comment by mansona** [comment]
wow, nice catch 😱 

Maybe it's time that we move the guidemaker-ember-template to use https://github.com/empress/ember-showdown-prism and see if it still has the same issue 🤔 

Just for a bit of context ember-showdown-prism is the "future" of the implementation of the code blocks in the guides and it solves one of the major issues, where the code blocks aren't highlighted until after the JS loads (i.e. not in fastboot)

I wonder if the fact that we're changing how it works with ember-showdown-prism will just automatically fix this problem 🤔

**Comment by locks** [comment]
This seems fixed! Thanks for reporting 💪
