### ISSUE TITLE
Add code editors section to the Ember Guides

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1549]
In the Ember Guides, we have a spot in the table of contents for Developer Tools. We need to add a new topic "Code editors," which has one article inside. That article should tell people about helpful editor integrations.

You can base it on some previously drafted Atlas content: https://www.notion.so/Editors-Tooling-5da96f0b2baf4ce1bf3fd58e3b60c7f6

Aim for one paragraph per editor, plus useful links. This is intended to be an overview, not an exhaustive guide.

Edit - an MVP for this could be copying & pasting the old content from the old CLI Guides and removing outdated info. See [this guide](https://ember-cli.com/editors)

**Comment by fozy81** [comment]
Hi @jenweber I'd be interested to start drafting something for this issue.

**Comment by jenweber** [comment]
Awesome, thank you! Feel free to open a PR when you have a draft. It is the easiest way to get feedback as you work!

**Comment by jenweber** [comment]
Hi @fozy81, how is it going? Let us know if you have any questions or want to do some pairing on this one.

**Comment by fozy81** [comment]
Hi @jenweber , it's going well, but was a little busy last week but worked on draft last night. I did a bit of digging into what extensions are available. We maybe need some feedback on which extensions are most useful or which ones have been missed or no longer maintained etc. I use VS code but I'm quite new to that one. And know less about the other editors.

I'd appreciate feedback on the draft PR. Also be great to do some pairing at some point be useful to get some tips and tricks!

**Comment by mansona** [comment]
the PR was merged 🎉  thanks for doing the work
