### ISSUE TITLE
Document how to use caching primitives in Ember 3.15 - 3.21

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/guides-source#1551]
## Description

The [Autotracking In-Depth - Caching of tracked properties](https://guides.emberjs.com/release/in-depth-topics/autotracking-in-depth/#toc_caching-of-tracked-properties) shows how to use `createCache` and `getValue` to cache the value of a function.

The caching API is natively available to Ember starting version `3.22`. Between versions `3.13` and `3.21`, a developer has to install [ember-cache-primitive-polyfill](https://github.com/ember-polyfills/ember-cache-primitive-polyfill).

## TODOs

- [ ] Please add the following paragraph to the _end_ of the `Caching of tracked properties` section.

    ```markdown
    The cache API was released in Ember 3.22. If you want to leverage this API between versions 3.13 and 3.21, you can install [ember-cache-primitive-polyfill](https://github.com/ember-polyfills/ember-cache-primitive-polyfill) to your project.
    ```

    A list of files to update:

    - `guides/v3.15.0/in-depth-topics/autotracking-in-depth.md`
    - `guides/v3.16.0/in-depth-topics/autotracking-in-depth.md`
    - `guides/v3.17.0/in-depth-topics/autotracking-in-depth.md`
    - `guides/v3.18.0/in-depth-topics/autotracking-in-depth.md`
    - `guides/v3.19.0/in-depth-topics/autotracking-in-depth.md`
    - `guides/v3.20.0/in-depth-topics/autotracking-in-depth.md`
    - `guides/release/in-depth-topics/autotracking-in-depth.md`

**Comment by mahmoodhosseini** [comment]
Hi, I can take this.

**Comment by ijlee2** [comment]
@mahmoodhosseini Thanks! If you have any questions about setting up the project locally, please let me know.
