### ISSUE TITLE
Backport the updated Built-in Components page to 3.16 and 3.20 LTS

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1556]
This issue is good for new contributors. There was a bug in Ember for handling event names for the `<Input>` and `<Textarea>` components, and it's fixed now in versions 3.16, 3.20, and 3.21 of Ember. We already made some updates to the Guides for version 3.21, but the changes need to be copied over into v3.16 and v3.20. The work for this ticket is copy-paste and not any new writing.

To do:
- Copy the contents of the `release` version of `built-in-components.md`, found [here](https://github.com/ember-learn/guides-source/blob/master/guides/release/components/built-in-components.md), `release/components/built-in-components.md`
- Replace the contents of `v3.16.0/components/built-in-components.md` and `v3.20.0/components/built-in-components.md` with the updated content that you copied

Thanks for your help! If you are working on this issue, please add a comment so that others know to look for another issue to work on.

**Comment by ijlee2** [comment]
Important: You can copy-paste the entire file, but please make sure to update all links that point to `api.emberjs.com` to show the correct version, not `release`.

```markdown
# After copy-paste

Out of the box, Ember provides 2 components for building a form:

* [`<Input>`](https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Input?anchor=Input)
* [`<Textarea>`](https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Textarea?anchor=Textarea)

# Update the version in the API links (e.g. for `guides/v3.16.0`)

Out of the box, Ember provides 2 components for building a form:

* [`<Input>`](https://api.emberjs.com/ember/v3.16/classes/Ember.Templates.components/methods/Input?anchor=Input)
* [`<Textarea>`](https://api.emberjs.com/ember/v3.16/classes/Ember.Templates.components/methods/Textarea?anchor=Textarea)
```

**Comment by hbutau** [comment]
Hello @jenweber @ijlee2 , I am taking this one.

**Comment by ijlee2** [comment]
Thanks, @hbutau ! If you have questions, feel free to ask us!
