### ISSUE TITLE
[docs] update dependencies section to include ember-auto-import

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-learn/guides-source#1559]
It would be great if guides-source/guides/release/addons-and-dependencies/index.md were updated to showcase ember-auto-import instead of app.import.

**Comment by ijlee2** [comment]
Hi, @gabrielcsapo. Can you elaborate what are the changes that you wanted to see?

Currently, the [Managing Dependencies](https://guides.emberjs.com/release/addons-and-dependencies) section has 2 separate subsections:

- [Regular npm packages](https://guides.emberjs.com/release/addons-and-dependencies/#toc_regular-npm-packages), which mentions mention `ember-auto-import` and links to its `README`
- [Compiling Assets](https://guides.emberjs.com/release/addons-and-dependencies/#toc_compiling-assets), for "dependencies that are not included in an addon"

I guess I'm unsure what problem you might have encountered with `app.import`. If you can provide further information, that'd be great!

**Comment by gabrielcsapo** [comment]
👋 thanks for looking into this @ijlee2! I should have been more specific but some of sections that showcase app.import can be removed entirely with the suggestion that the way to import commonjs modules via ember-auto-import instead of app.import.

**Comment by ijlee2** [comment]
@gabrielcsapo Thanks! I've been pulled in different directions lately so I haven't gotten to think about the issue yet, my bad.

If you have an idea for what the pull request could look like, would you be interested in working on it? After you open the PR, I can help with proofreading and suggesting changes.

**Comment by locks** [comment]
@gabrielcsapo wanna give it a go?

**Comment by locks** [comment]
Actually, let's move the conversation to https://github.com/ember-learn/guides-source/issues/1638. Thanks!
