### ISSUE TITLE
Add link to CLI Guides in Getting Started

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1560]
## Description

In the `Getting Started - How to Use the Guides` section, the link for `Ember CLI` points to `Configuration - Configuring Ember CLI` section. The latter (configuring your app ) is an advanced topic and doesn't show much information.

Please link to the CLI Guides (https://cli.emberjs.com/release/) instead.

## TODOs

- [ ] Update the Markdown file `guides/release/getting-started/index.js`:

    ```markdown
    <!-- Before -->
    * [Ember CLI](../configuring-ember/configuring-ember-cli/) - A robust development toolkit to create, develop, and build Ember applications. When you see a command `$ ember <command>` instruction throughout the guides, that's Ember CLI!

    <!-- After -->
    * [Ember CLI](https://cli.emberjs.com/release/) - A robust development toolkit to create, develop, and build Ember applications. Learn [basic commands](https://cli.emberjs.com/release/basic-use/cli-commands/) from the CLI Guides.
    ```

- [ ] Make the same changes to previous versions of Ember, starting with `v3.15.0`:

    - `guides/v3.15.0/getting-started/index.js`
    - `guides/v3.16.0/getting-started/index.js`
    - `guides/v3.17.0/getting-started/index.js`
    - `guides/v3.18.0/getting-started/index.js`
    - `guides/v3.19.0/getting-started/index.js`
    - `guides/v3.20.0/getting-started/index.js`
    - `guides/v3.21.0/getting-started/index.js` (assuming the Ember Guides shows `v3.22` for `release`)

## Screenshots

Getting Started - How to Use the Guides:

<img width="1680" alt="getting-started" src="https://user-images.githubusercontent.com/16869656/95632010-5c759700-0a4a-11eb-9b4a-b5541f86c1f6.png">

Configuration - Configuring Ember CLI:

<img width="1680" alt="configuring-ember-cli" src="https://user-images.githubusercontent.com/16869656/95632158-a494b980-0a4a-11eb-9f25-fc4a0176e98d.png">

**Comment by ijlee2** [comment]
Assigned to @hbutau

**Comment by ijlee2** [comment]
Completed
