### ISSUE TITLE
Explain how to transition between Routes

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#157]
We should add a section to [Defining your routes](https://guides.emberjs.com/release/routing/defining-your-routes/) that very briefly explains how to move between routes, and link to the API docs

There are 3 main ways:
- `this.transitionTo` or `transitionToRoute` from a route
- using the Router Service
- link to in a template

**Comment by ynotdraw** [comment]
Hey @jenweber, I'd love to take a stab at this!

**Comment by jenweber** [comment]
Closed with merging #196 🎉
