### ISSUE TITLE
Backport changes to Specifying a Route's Model

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/guides-source#1572]
## Problem

Today, the Learning Team found a few typos and duplicate content in [Routing - Specifying a Route's Model](https://guides.emberjs.com/release/routing/specifying-a-routes-model/).

We fixed the issue for the `release` directory (Ember `v3.21` at the time of writing). We'd like to see the changes backported to `v3.15` - `v3.20`.

## TODOs

- [ ] Study the [changes made in the pull request](https://github.com/ember-learn/guides-source/pull/1571/files) for `release` directory.

- [ ] Apply the same changes to the following files:

    - `guides/v3.15.0/routing/specifying-a-routes-model.md`
    - `guides/v3.16.0/routing/specifying-a-routes-model.md`
    - `guides/v3.17.0/routing/specifying-a-routes-model.md`
    - `guides/v3.18.0/routing/specifying-a-routes-model.md`
    - `guides/v3.19.0/routing/specifying-a-routes-model.md`
    - `guides/v3.20.0/routing/specifying-a-routes-model.md`

**Comment by ijlee2** [comment]
Hi, everyone. I created this issue for [EmberFest Contributors Workshop](http://emberfest.eu/), to be held on October 16. Please allow a workshop participant the chance to claim and work on this issue first.

If the issue is still open after October 16, anyone is welcome to sign up for the issue. Thanks, and happy Hacktoberfest! 🎃

**Comment by JamesS-M** [comment]
@ijlee2 I can tackle this!

**Comment by ijlee2** [comment]
@JamesS-M Thank you in advance for your help!
