### ISSUE TITLE
Link to "Patterns for Components" and "Patterns for Actions" from the main components section

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1573]
We have these really great articles, [Patterns for components](https://guides.emberjs.com/release/in-depth-topics/patterns-for-components/) and [Patterns for actions](https://guides.emberjs.com/release/in-depth-topics/patterns-for-actions/), but you can only get to them from the nav bar! Let's add a section to [Component State and Actions](https://guides.emberjs.com/release/components/component-state-and-actions/) that links to these resources.

To do:
- Add a "Learn more" heading to the bottom of Component State and Actions (only make changes to the file that is in the `release` folder, and not older versions)
- Link to the two "patterns" articles with a one sentence description of each.

Links have kind of a funny syntax in the Guides. They should be relative links, such a `../../some-topic/article-name`. You will probably need to go up one more level than you would expect in your relative link in order to get it to work. If you need help figuring out the right thing, just ask when you open your PR.

**Comment by Ian-Yy** [comment]
Hello, may I take this up?

**Comment by ijlee2** [comment]
@Ian-Yy Thank you for your interest in helping out with the Ember Guides! If you have questions, feel free to reach out in this issue or over [Ember Discord](https://discord.gg/emberjs).

**Comment by Ian-Yy** [comment]
Created a PR. Please let me know if its not suitable and need changes. Thanks
