### ISSUE TITLE
Remove the link to the "guides-app" repo and add the CLI Guides

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1575]
The [Repositories](https://guides.emberjs.com/release/contributing/repositories/) page is out of date. Here are some changes to make!

- The guides-app repo is deprecated, and so the link to https://github.com/ember-learn/guides-app should be removed
- Add a link for the CLI Guides, https://github.com/ember-learn/cli-guides 
- Add a link to the deprecations guide repo https://github.com/ember-learn/deprecation-app/ and website https://deprecations.emberjs.com/

You should only make changes to the file that is in the `release` folder, and not older versions of Ember.

**Comment by cah-johnryan** [comment]
EmberFest Contributors Workshop: I am going to take a shot at this now
