### ISSUE TITLE
Explicitly inject store service in Octane examples

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/guides-source#1576]
## Background

Currently, [Ember Data injects the `store` service](https://github.com/emberjs/data/blob/v3.21.1/packages/-ember-data/addon/setup-container.js#L44-L48) into controllers and routes for us. In Octane and the future, we want the code to show their intent clearly.

```javascript
// Before
model() {
  return this.store.findAll('photo');
}

// After
@service store;

model() {
  return this.store.findAll('photo');
}
```

## Problem

Several examples in the Ember Guides already follow the practice of explicitly injecting the `store` service. However, there are also many that rely on implicit injection still.

In Part 1, we'll update code examples in the `release` directory. Once the pull request is merged, in Part 2, we'll backport the changes to `v3.15.0` to `v3.20.0`.

## TODOs

To help with reviewing your pull request, I **highly encourage** you to push a commit after editing 1 Markdown file. You would have a total of 6 commits.

- [ ] Explicitly inject the `store` service to the following examples in `guides/release` directory. You will need to add the missing import statement:

    ```javascript
    import { inject as service } from '@ember/service';
   ```

    - [models/handling-metadata.md](https://guides.emberjs.com/release/models/handling-metadata/)
        - Line 66.`app/routes/users.js`

    - [models/pushing-records-into-the-store.md](https://guides.emberjs.com/release/models/pushing-records-into-the-store/)
        - Line 133. `app/routes/confirm-payment.js`

    - [routing/defining-your-routes.md](https://guides.emberjs.com/release/routing/defining-your-routes/)
        - Line 330. `app/routes/some-route.js`

    - [routing/loading-and-error-substates](https://guides.emberjs.com/release/routing/loading-and-error-substates/)
        - Line 25. `app/routes/slow-model.js`
        - Line 107. `app/routes/user-slow-model.js`
        - Line 222. `app/routes/articles-overview.js`

    - [routing/query-params.md](https://guides.emberjs.com/release/routing/query-params/)
        - Line 143. `app/routes/articles.js`

    - [routing/specifying-a-routes-model.md](https://guides.emberjs.com/release/routing/specifying-a-routes-model/)
        - Line 119. `app/routes/songs.js`
        - Line 251. `app/routes/album/index.js`
        - Line 289. `app/routes/album.js`

**Comment by ijlee2** [comment]
Hi, everyone. I created this issue for [EmberFest Contributors Workshop](http://emberfest.eu/), to be held on October 16. Please allow a workshop participant the chance to claim and work on this issue first.

If the issue is still open after October 16, anyone is welcome to sign up for the issue. Thanks, and happy Hacktoberfest! 🎃

**Comment by Rxbsxn** [comment]
I will handle that one!

**Comment by ijlee2** [comment]
Hi, @Rxbsxn. Thank you for your help!
