### ISSUE TITLE
Say explicitly what kind of Query Parameters are being taught

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#158]
It's common for new learners to confuse API request query parameters (Ember Data) with routing query parameters.

Add a couple sentences to the intro section of [Query Params](https://guides.emberjs.com/release/routing/query-params/) to indicate that in web development, query params can be one of two things, either in the url or for making API requests. In Ember, these are two separate concepts. Link to Ember Data query params rather than explaining what they are. It's important that we don't make readers more confused.

Please make changes to only the markdown files for the latest Ember version.

**Comment by Parrryy** [comment]
I'll pick this up! 👍

**Comment by jenweber** [comment]
Closed by merging #201
