### ISSUE TITLE
Add one sentence to say what a helper is

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#159]
This section on handlebars mentions helpers without saying what they are. Add one sentence to give new learners an idea, so they don't have to dig into handlebars docs. You might find a good definition in the API docs, or you could use this definition from the "built-in helpers" guide, which is "A helper is usually a simple function that can be used in any template."

[Here is the section](https://guides.emberjs.com/release/templates/handlebars-basics/#toc_helpers)

Keep in mind that someone would likely read this definition before they get to Components.

Please only make changes to the markdown files for the latest version of Ember.

If you are an experienced Ember dev and you want to do this issue, when you are done, see if you can find another small change that would be good for a new contributor to do, and open an issue on it! Thanks!

**Comment by John-E5** [comment]
I'd like to take this on.

**Comment by jenweber** [comment]
Awesome, all yours! If you want it to count for Hacktoberfest, open your PR on or after Oct 1st. Thanks for your help!

**Comment by John-E5** [comment]
That's great ill submit the PR tomorrow so.

**Comment by John-E5** [comment]
Requested changes have been added.
