### ISSUE TITLE
Diff is hard to read and use in code examples

### ISSUE THREAD

**Issue by kategengler** [ember-learn/guides-source#1604]
For example: https://guides.emberjs.com/release/components/helper-functions/#toc_advanced-class-helpers

It is very hard to see here what the proper syntax is for a class-based helper. You cannot just copy the correct syntax out of the example. 

I've seen this problem elsewhere in the Guides as well, but this example seemed particularly bad because it's not something where a user is adding to an earlier example, but just a different syntax to what was generated.

**Comment by chancancode** [comment]
Would https://github.com/ember-learn/guides-source/issues/1534#issuecomment-694594680 work for you? (also this is probably a duplicate of that issue)

**Comment by kategengler** [comment]
Ah, that'd be great! I'll close this in favor of that.
