### ISSUE TITLE
Rework "Defining a Component Subclass"

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#161]
I don't really understand what this section is trying to say. Do you know? Add or edit to make it easier to understand!

[Defining a component subclass](https://guides.emberjs.com/release/components/defining-a-component/#toc_defining-a-component-subclass)

Please make changes to only the markdown file for the latest version of Ember. I can't provide more guidance on how to rewrite this, but if you drop by the learning team channel in Discord, others may have more ideas. [Link to join](https://www.emberjs.com/community/)

**Comment by CosmicWebServices** [comment]
Got this one.

**Comment by jenweber** [comment]
Closed by merging #172
