### ISSUE TITLE
v3.22 algolia search does not yield any(?) results

### ISSUE THREAD

**Issue by MichalBryxi** [ember-learn/guides-source#1610]
Tried to search on [v3.22 guides](https://guides.emberjs.com/v3.22.0/) for any generic Ember term from `modifiers` through `component` to `template` provides no results whatsoever (see screenshot below).

Compared that to `v3.21`, `v3.20` and `v3.19` which all works ok.

![Screenshot 2020-11-28 at 23 37 04](https://user-images.githubusercontent.com/847473/100528282-5b0b5400-31db-11eb-8850-dfef35da9f2b.png)

**Comment by ijlee2** [comment]
@MichalBryxi Thanks for reporting the issue.

@locks will try to set aside time to look into the problem. We're hoping that we can fix the search issue for 3.22 when Ember Guides releases its 3.23 documentation.

**Comment by locks** [comment]
I had some time to look into this and it should now be working:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/32344/101110879-e74dba80-35d1-11eb-9a6a-6cb33412d2f8.png">

Hard refresh and give it a go! If it's still not working please re-open for further investigation.

**Comment by ijlee2** [comment]
I checked that the search in 3.22 works. Much thanks, @locks!
