### ISSUE TITLE
Explain how to pass actions and then use actions that have been passed

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#162]
There are a few different ways to pass actions in Ember. We don't realllly teach them in the Guides, though it's covered in the Tutorial.

To do:
- [ ] link to [this section](https://guides.emberjs.com/release/components/triggering-changes-with-actions/#toc_passing-the-action-to-the-component) on passing actions to components from [here](https://guides.emberjs.com/release/components/passing-properties-to-a-component/)
- [ ] include a note that actions can't be passed down from a route, only from a controller or another component

Changes should only be made to the markdown files for the latest version of Ember.

**Comment by Parrryy** [comment]
I'd be happy to pick this up :)

**Comment by jenweber** [comment]
Closed by https://github.com/ember-learn/guides-source/pull/177, thank you!
