### ISSUE TITLE
Add back meta image

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/guides-source#1621]
We've lost the meta image for guides links, e.g. https://twitter.com/Steady5063/status/1340297223733735426

<img width="595" alt="screenshot" src="https://user-images.githubusercontent.com/16869656/111861683-79df5300-8950-11eb-8364-871b10d8485b.png">

Relates to / probably same fix as: https://github.com/ember-learn/ember-blog/issues/854

**Comment by ijlee2** [comment]
@nickschot @mansona Can you have a look at this issue? I checked that `e` logo does not show up still.

**Comment by amyrlam** [comment]
Ah thanks for the reminder. I added it to ember-website with https://github.com/ember-learn/ember-website/pull/804, by hardcoding the path...because I noticed the emberjs and embertimes Twitter accounts sending out links with a blank image. 

I made a similar change here: https://github.com/ember-learn/guides-source/pull/1647 and will tag you 3 on that PR.
