### ISSUE TITLE
Algolia search provides no results

### ISSUE THREAD

**Issue by MichalBryxi** [ember-learn/guides-source#1625]
## Problem description

1. GOTO: https://guides.emberjs.com/release/
2. Try to put "route" into search box.
3. No results are found even though this is a very common keyword

## What should happen instead

Search provides some results

## Screenshots

<img width="619" alt="Screenshot 2021-01-10 at 23 25 32" src="https://user-images.githubusercontent.com/847473/104138357-77360f80-539b-11eb-9c16-4693ab9fb17a.png">

## Additional info

Seems like guides hit a limit with Algolia API:

<img width="647" alt="Screenshot 2021-01-10 at 23 25 54" src="https://user-images.githubusercontent.com/847473/104138364-81f0a480-539b-11eb-824a-41cbf0a75ce5.png">

**Comment by jaredgalanis** [comment]
Thanks for reporting this @MichalBryxi! I've notified Algolia support of the issue and will look into it further. I'll report back here once I've figured out what the problem is.

**Comment by jaredgalanis** [comment]
Search is back up. I have not looked at the cause yet, but will.
