### ISSUE TITLE
Link to the section on Query Parameters from the Controller guide

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#163]
The opening paragraph of [Controllers](https://guides.emberjs.com/release/controllers/) should mention that they are the place to define routing query parameters, and link to [this page](https://guides.emberjs.com/release/routing/query-params/)

You should only make changes to the markdown file for the latest version of the guides.

If you are an experienced contributor, when you are done with this issue, please look for another small change that would be good for a new contributor, and open an issue on it. Thanks!

**Comment by Parrryy** [comment]
I'd be happy to pick this up.

**Comment by jenweber** [comment]
Closed by merging #173
