### ISSUE TITLE
Quick Start Guide: Post Deployment to Netlify, Navigating to Routes Resulted in Page Not Found 

### ISSUE THREAD

**Issue by waihon** [ember-learn/guides-source#1645]
After following the steps under "Deploying to Netlify using drag and drop" to deploy the app, navigating to `/` resulted in the index page as expected.

However, navigating to `/scientists` and `/programmers` resulted in Page Not Found error.

I posted the issue to Ember.js' Discord for help and received feedback that it might be due to missing of a `_redirects` file under `dist/` directory.

I had created such a file and added below line to that file:
`/*   /index.html   200`

... followed by re-deploying `dist` using drag and drop. Now that the `/scientists` and `/programmers` work as expected.

I was advised by a community member to open an issue here to improve the deployment section of the Ember.js Guides.

**Comment by waihon** [comment]
After further study, instead of adding a `_redirects` file into `dist/` after a build, it would be better to add that file to `public/` instead.
That way, `ember build --environment=production` will add `public/_redirects` to `dist/` automatically, for deployment using "drag and drop" or "GitHub".

**Comment by waihon** [comment]
I hope this issue will be assigned a much higher priority as it involves the Getting Started guide. A good first impression would be important for some aspiring Ember.js developer to continue pursuing this framework instead of switching to other front-end frameworks.

**Comment by ijlee2** [comment]
@waihon Hello, thank you for letting us know that the instructions for deploying to Netlify in the Quick Start need an additional step. I agree that we do need to explain the missing step.

I think these reference links may help us come up with the content for the missing step:

- https://docs.netlify.com/routing/redirects/
- https://devjournal.balinterdi.com/how-to-deploy-an-ember-app-to-netlify/
- https://github.com/shipshapecode/ember-cli-netlify

@rwwagner90 I feel like you may be able to help the best with explaining the step in the Quick Start. Could I assign this issue to you?

**Comment by rwwagner90** [comment]
@ijlee2 should we perhaps add something that mentions using https://github.com/shipshapecode/ember-cli-netlify? This feels more like the "Ember way" to configure things than manually maintaining the `_redirects` file.

**Comment by ijlee2** [comment]
@rwwagner90 I'm ok with mentioning `ember-cli-netlify` in the Guides. Since the page is Quick Start, I think it's best to provide readers an option that just works.

It may be good to also add the link to https://docs.netlify.com/routing/redirects/ in case people want to learn more about how redirects work?

**Comment by jenweber** [comment]
I'd like if we can describe both, if it's not too confusing/wordy. The reason is that I think it's good to demonstrate that you don't need anything special to get your app deployed, but there is a bunch of stuff that helps you out if you look for it. For example:

```
The last step is to let your web app server know how to handle urls. For Netlify, here are two options. You can create a file called `_redirects` and put xyz in it. Or, you can use tools created by the community to help make deploying easier, and install [ember-cli-netlify](https://github.com/shipshapecode/ember-cli-netlify). 
```

**Comment by jenweber** [comment]
As a sidenote, I'd also be happy to merge a PR that mentions one option instead of both, just to get this fixed ASAP for our readers. It should be as short and sweet as possible so that we don't confuse people, so linking out to other resources for more learning is a great suggestion.

**Comment by rwwagner90** [comment]
@jenweber I defer to whatever the group prefers, but I personally think configuring it in `ember-cli-build.js` with `ember-cli-netlify` feels like "the Ember way", but I know we also want to remove some of the Ember magic, so I am fine with whatever.

**Comment by fozy81** [comment]
@jenweber I've made a PR mentioning the adding _redirect file and linking to other resources. Please review.

**Comment by fozy81** [comment]
@rwwagner90  - sorry, just noticed this is assigned to you. I got confused with the 'help wanted' tag and just jumped in. Anyway, hopefully the PR is a good starting place.

**Comment by ijlee2** [comment]
@fozy81 No problem. I'm glad that you were able to step in and help.
