### ISSUE TITLE
Testing improvements - update Percy test code to snapshot more pages

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/guides-source#1650]
From @mansona at Learning Team meeting with @jaredgalanis @locks . Issue details edited by @jenweber 

In [`visual-regression-test.js`](https://github.com/ember-learn/guides-source/blob/master/tests/acceptance/visual-regression-test.js) we loop over pages in the table of contents and take a visual snapshot of them using a service called Percy. Percy lets us compare a visual diff between two screenshots of the app - old and new - as part of our testing strategy. It helps us catch unintended visual bugs. The visual regression test script looks two levels deep, however we have [some pages that are three levels deep](https://guides.emberjs.com/release/upgrading/current-edition/).

To do:
- The test code should loop through and look for children (assumes 2 levels, need 3) 
- Can use async/await instead of reduce, if you want

Tips for working on this:
Percy tests won't run locally for you, but you can still check which pages would be snapshotted. Replace [this line](https://github.com/ember-learn/guides-source/blob/b7a68763c918e97f0aeb6008a3a56b2b459a05c0/tests/acceptance/visual-regression-test.js#L39) with a console log and see if your code changes result in more pages being snapshotted. When you push your code up to GitHub and open a PR, you can see the snapshots there.

**Comment by barelyknown** [comment]
Taking a look at this one.
