### ISSUE TITLE
Remove references to Travis and replace them with more generic words

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1658]
Travis is a Continuous Integration Testing service. We don't use Travis as much anymore for Ember projects, but we have some lingering references. We use GitHub Actions a lot now. We should say something more generic when we talk about CI, like "Continuous integration tests" or "automated tests" etc. 

## To do:
- Remove references to Travis here: https://guides.emberjs.com/release/contributing/#toc_travis-testing
- Search the `release` directory for any more references and fix them if you find any.

## Tips
- Only make changes to the file in the release directory. You should leave older verisons as-is.
- When you open a PR, you should expect the Percy tests to fail - this is because there's a visual difference in the guides due to your writing, and that's a good thing! Maintainers will review the diff and approve or request changes, so you don't need to worry about it.

**Comment by vivasconcelos** [comment]
I'll help with that!

**Comment by ijlee2** [comment]
Completed in #1664
