### ISSUE TITLE
Add a very simple example to the top of Block Content

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1659]
[This article](https://guides.emberjs.com/release/components/block-content/) gives a thorough explanation of what block component content is and when to use it, but it's missing a quick intro to help someone recognize what Block Content looks like.

## To do:
- Add a super short example to the intro to block content. See suggestions below
- Only make your changes in to the file in the Release folder: https://github.com/ember-learn/guides-source/blob/master/guides/release/components/block-content.md

## Suggestions

_Something like this might do the trick. Feel free to edit or do something totally different._

Component templates can leave a placeholder that users of the component can fill with their own HTML. This is called Block Content, and it looks like this:

```
<MyComponent>
    Here is some block content! It will show up in the `{{yield}}` section in the template for MyComponent.
</MyComponent>
```

What is this content style for, and how can you use it to write components? To make that more concrete, let's take a look at two similar components representing different user's messages. (And leave the rest of the content as-is)

**Comment by barelyknown** [comment]
I'll handle this as part of the EmberConf contributors' workshop.
