### ISSUE TITLE
Mention built-in helpers at the start of the Helpers page

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1660]
[This page](https://guides.emberjs.com/release/components/helper-functions/) of the Guides jumps right into making you write your own helper. This is a very useful skill and helps build understanding of helpers, but it's good if developers also know upfront that Ember has some built-in helpers.

## To do
- In the intro section of [this file](https://github.com/ember-learn/guides-source/edit/master/guides/release/components/helper-functions.md), right after "you can use helper functions..." mention that you can write your own helpers or use built-in helpers, and add a link to the section later in this article that describes the built-ins. The link should go to `#toc_built-in-helpers` (it should be a relative link)

## Tips

- Only make changes to the file in the release directory. You can leave older verisons as-is.
- When you open a PR, you should expect the Percy tests to fail - this is because there's a visual difference in the guides due to your writing, and that's a good thing! Maintainers will review the diff and approve or request changes, so you don't need to worry about it.

**Comment by Valgueiro** [comment]
I'll try to do it during the EmberConf 2021 workshop! 😄
