### ISSUE TITLE
Link to ember-auto-import in "Managing Dependencies"

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#167]
We don't actually show new devs how to use `npm` packages. We should.

This is somewhat the domain of `ember-cli` instead, but I think in the interim, we should link to [ember-auto-import](https://github.com/ef4/ember-auto-import) in the [managing dependencies](https://guides.emberjs.com/release/addons-and-dependencies/managing-dependencies/) guide. The explanation should be clear that there are many valid approaches to loading in dependencies, but it's the easiest for new developers.

I asked Ed about this a while back and he's fine with it.

To do:
- [ ] link to ember auto import and add a very brief explanation (2-3 sentences). See if you can do this without creating a new heading
- [ ] make changes to only the markdown file for the latest ember version

**Comment by John-E5** [comment]
I'll take this on
