### ISSUE TITLE
Update the Ember extensions / code editor page

### ISSUE THREAD

**Issue by fozy81** [ember-learn/guides-source#1682]
There's been a few [suggestions](https://discord.com/channels/480462759797063690/814921339219476571/831275779643539467) to improve the [Ember extensions / code editor page](https://guides.emberjs.com/release/code-editors/).

These are:

- [x] Merge the Vim and Neovim sections as same plugins can be used in both editors
- [x] Make it clear that the 'unstable' language server is safe to use...in other words it is...stable :confused: .
- [ ] Add in other extensions such as VS  ember-template-lint-plugin-tailwindcss ?

I'm happy to draft a PR for these changes, any suggestions/feedback welcome :+1: .

**Comment by ijlee2** [comment]
The suggested items sound good to me, with the possible exception of the 3rd item. Rather than "other extensions" (a vague list), I'd suggest adding `ember-template-lint-plugin-tailwindcss` if it's used enough, or not adding it for now if it isn't used enough.

Can you start working on a pull request? Thanks!

**Comment by fozy81** [comment]
Thanks @ijlee2 , I'll start work on a PR. And do a little more research on the most popular extensions being used at the moment.

**Comment by fozy81** [comment]
@ijlee2 I've updated the page (with 120 column width formatting) and made changes for the 1st and 2nd items in the issue.

> The suggested items sound good to me, with the possible exception of the 3rd item. Rather than "other extensions" (a vague list), I'd suggest adding `ember-template-lint-plugin-tailwindcss` if it's used enough, or not adding it for now if it isn't used enough.
> 
> Can you start working on a pull request? Thanks!

The 3rd item: I've not added any more extensions. We can seek more feedback on this in future?

But I have removed mention of:
- [els-addon-docs](https://github.com/lifeart/els-addon-docs)
- [els-addon-typed-templates](https://github.com/lifeart/els-addon-typed-templates)

These two _add-ons_ were previously under the Neovim section. But they are in fact add-ons (not extensions in their own right)  for unstable ember language server extension. So it was a bit confusing mentioning them in the Neovim section. And they are listed on the  [unstable ember language server](https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable) web page for those who are curious.

Please review/feedback.

**Comment by ijlee2** [comment]
@fozy81 Let's close this issue after merging #1683. If there's a need to mention more extensions in the future, people are welcome to open a new issue.

I don't know much about `els-addon-docs` and `els-addon-typed-templates`, but think it makes sense to remove them if they are addons for unstable ELS and the unstable ELS' webpage mentions them. We can always revert changes at a later point if needed.
