### ISSUE TITLE
Add instructions for contributing to API documentation

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1690]
We have this page in the Guides to help people contribute: https://guides.emberjs.com/release/contributing/ But it's missing instructions for a common task: people want to know how to add/change api docs. We should add a new section to this page describing the workflow:

1. Open up the source code for ember or ember-data (give links)
2. Find the existing docs within it (give advice on how to search)
3. Describe what to branch from and how to structure the commit messages/subject line

**Comment by fozy81** [comment]
Hi @jenweber , I'd like to try to add this guidance.

**Comment by fozy81** [comment]
Hi @jenweber - I've jumped in and prepared a PR, hopefully a useful starting place.
