### ISSUE TITLE
"Later on" comment feels confusing in "Native classes in-depth" section

### ISSUE THREAD

**Issue by jacobq** [ember-learn/guides-source#1694]
In the [Native Classes In-Depth](https://github.com/ember-learn/guides-source/blob/master/guides/release/in-depth-topics/native-classes-in-depth.md) part of the guides it says:

> Ember provides a number of decorators, such as the `@tracked` decorator, that will be described in greater detail later on in the guides.

but it's not obvious to me where "later on in the guides" is because this is the end of the in-depth topics section which is the end of the core concepts guide. The [Autotracking In-Depth](https://guides.emberjs.com/release/in-depth-topics/autotracking-in-depth/) page 3 topics back talks about it though as does [Component State and Actions](https://guides.emberjs.com/release/components/component-state-and-actions/) (even earlier), and the [Tracked Properties](https://guides.emberjs.com/release/upgrading/current-edition/tracked-properties/#toc_backwards-compatibility) page (in the octane upgrade guide in the additional resources list way at the end). I think it would be nice if there could be some kind of cross-reference here or perhaps just removal of the phrase "later on" as this seems misleading to me if the left navigation can be taken as a topologically accurate representation of the linear flow of the guides.

Side-note: I actually stumbled across this page because I was looking for a section about computed macros like `alias`, `filterBy` etc. (not sure where this went, if that's no longer encouraged, etc.) and found them [in the API docs](https://api.emberjs.com/ember/3.26/modules/@ember%2Fobject#functions-computed) instead

**Comment by jenweber** [comment]
I agree, this should be a link.

```
Ember provides a number of decorators, such as the [@tracked decorator](link to auto tracking).
```

**Comment by jenweber** [comment]
Thanks for the feedback and suggestion!

**Comment by rajakvk** [comment]
I will work on this issue. @jenweber

**Comment by jonr-luma** [comment]
Hi there! Can this issue be closed? It looks like the PR to fix it was merged in already.
