### ISSUE TITLE
Outdated rootElement management example

### ISSUE THREAD

**Issue by lifeart** [ember-learn/guides-source#1719]
![image](https://user-images.githubusercontent.com/1360552/130924746-cfb0f945-5efe-4e2f-bf28-22fb144bb471.png)

https://guides.emberjs.com/release/configuring-ember/embedding-applications/

Latest blueprint:

![image](https://user-images.githubusercontent.com/1360552/130924812-73fa25e2-72bd-48b8-9f5c-7d72fc762214.png)

**Comment by locks** [comment]
This seems to be fixed! Let me know if I missed anything.
