### ISSUE TITLE
Release script is broken

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1736]
Results of running `npm run release:guides:minor`

> scripts/create-new-minor-version: line 82: create-new-guides-version-919: command not found
> 👩‍💻 Create pull request for : https://github.com/ember-learn/guides-source/compare/master...create-new-guides-version-919
> Press any key to continue
> 🤖 Restoring previous branch.
> You might see an error if you didn't have a stash.
> HEAD is now at cea329d2 v3.28.0
> Switched to branch 'master'
> Your branch is up to date with 'origin/master'.
> error: - is not a valid reference
> Deleted branch create-new-guides-version-919 (was cea329d2).
> error: refs/stash@{} is not a valid reference

I was able to create the PR myself because the branch push succeeded.

**Comment by locks** [comment]
@jenweber did you click the link in "Create pull request for :"? The person at a computer indicates it's a manual step.
