### ISSUE TITLE
Update "Ember Data: Introduction" guide

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#1755]
`<LinkTo` and `@tagName` are used in the content of this guide, but this is a deprecated API. See https://deprecations.emberjs.com/v3.x/#toc_ember-built-in-components-legacy-arguments for the deprecation and how to update the content.
This might need some learning team discussion for coherence and flow of the resulting content.

**Comment by jenweber** [comment]
Closed by https://github.com/ember-learn/guides-source/pull/1759/files
