### ISSUE TITLE
Doc(v3.16.0): route-params.md test failed image not visible

### ISSUE THREAD

**Issue by praveeno** [ember-learn/guides-source#1767]
In https://guides.emberjs.com/v3.16.0/tutorial/part-2/route-params/ url
The test failed image is not visible, also [image url](https://guides.emberjs.com/images/tutorial/part-2/route-params/fail@2x.png) is giving 404.
Issue in this file
[tutorial/part-2/route-params.md](https://github.com/ember-learn/guides-source/blob/3a8230bc5f5cc2e4b93adca99ddb574526a08f3d/guides/v3.16.0/tutorial/part-2/route-params.md?plain=1#L179)
[<img width="1256" alt="Screenshot 2022-01-12 at 2 00 54 PM" src="https://user-images.githubusercontent.com/19618730/149091716-9860e0da-ce0c-4551-8e75-d0d75fc4d418.png">](https://guides.emberjs.com/v3.16.0/tutorial/part-2/route-params/)

**Comment by praveeno** [comment]
same issue in [https://guides.emberjs.com/v3.16.0/tutorial/part-2/service-injection/](https://github.com/ember-learn/guides-source/blob/3a8230bc5f5cc2e4b93adca99ddb574526a08f3d/guides/v3.16.0/tutorial/part-2/service-injection.md?plain=1#L7)

**Comment by locks** [comment]
Thanks for reporting, we'll be taking alook shortly!

**Comment by jenweber** [comment]
Is this related to us pre-rendering some earlier versions?

**Comment by locks** [comment]
@jenweber I believe this happened because super-rentals-tutorials overwrites the assets folder, and since the most recent tutorial no longer has these assets, they got deleted.

**Comment by praveeno** [comment]
yes, I agree with @locks, image urls dont have any versions in url, so seems like assets folder override by latest version new build.

**Comment by locks** [comment]
Still happening.

**Comment by MinThaMie** [comment]
I get that this is not great, but we are not going to back port a fix that for back. I created an issue https://github.com/ember-learn/super-rentals-tutorial/issues/247 so that it's tracked at the source where we should fix this.
