### ISSUE TITLE
"Note about prop drilling / anti-patterns?"

### ISSUE THREAD

**Issue by kevinansfield** [ember-learn/guides-source#1768]
On the ["Patterns for actions"](https://guides.emberjs.com/release/in-depth-topics/patterns-for-actions/#toc_calling-actions-up-multiple-component-layers) page, in the "Calling Actions Up Multiple Component Layers" section, there's [the text](https://github.com/ember-learn/guides-source/blob/3a8230bc5f5cc2e4b93adca99ddb574526a08f3d/guides/release/in-depth-topics/patterns-for-actions.md?plain=1#L513):

> Note about prop drilling / anti-patterns?

It this meant as an internal note rather than a public one? Is there a resource somewhere that correlates to this note?

**Comment by jenweber** [comment]
This was resolved at some point in the past. Thanks for reporting!
