### ISSUE TITLE
Dev tools - index deploy script needs to skip pre-built guides

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1777]
When we build Algolia search indexes, it looks at what is in `public`, including our pre-built files, and tries to make indices for those too. We don't want that.

Options:
- The best way to handle this is in Guidemaker - would be good to have a feature where you can just say what version to deploy.
- Add a step to the search index script that deletes the contents of `public/v*`

**Comment by locks** [comment]
Fixed by https://github.com/ember-learn/guides-source/pull/1778.
