### ISSUE TITLE
A guide on how to handle promises with computed properties

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-learn/guides-source#180]
I think they should be a page on how to deal with promises when using computed properties, for example, I have this addon: https://emberobserver.com/addons/ember-computed-promise-monitor (though, diving in to this addon could be a neat post by itself).

But, also, there is the built in `PromiseProxy`

Basically, it needs to be clear when the value of a computed property is read, and when a "request for updated value" is made, and how promises and objects in general may mess up computed properties in some situations.

**Comment by abhilashlr** [comment]
@NullVoxPopuli I can write on it, but before I start, I just want to confirm if this will be a new page under `object-model`?

**Comment by jenweber** [comment]
Closed because we are moving towards tracked properties for Octane
