### ISSUE TITLE
Broken link to "tools for deprecations" on https://guides.emberjs.com/release/upgrading/

### ISSUE THREAD

**Issue by geneukum** [ember-learn/guides-source#1807]
On the page: https://guides.emberjs.com/release/upgrading/, there is a link to https://guides.emberjs.com/release/upgrading/release/ember-inspector/deprecations/ with the text "tools for deprecations." It doesn't seem like this page exists, as when I click the link, I am presented with a Page Not Found error. I'm not 100% sure, but I suspect that this is probably supposed to be linking to https://guides.emberjs.com/release/ember-inspector/deprecations/.

We should fix this up so that others are able to find the content that they're looking for a little easier.

**Comment by geneukum** [comment]
BTW, I'd be happy to submit a PR for this, but it would be really awesome if someone a little more familiar with the docs could confirm whether: https://guides.emberjs.com/release/ember-inspector/deprecations/ is the page that we want to link to.

**Comment by ijlee2** [comment]
Hi, @geneukum. Thank you for noticing the broken link issue and providing a suggestion.

I'm not sure if https://guides.emberjs.com/release/ember-inspector/deprecations/ had been the intended page, but think it's a good page to show regardless.

Could you open a pull request for the Learning Team to review? I think it'd be good if you can also fix the broken link, not just in the `guides/release`, but also in the folders corresponding to the previous versions.

When targeting the previous versions, you will want to watch out for the URL. For example,

- `https://guides.emberjs.com/release/ember-inspector/deprecations/` (for `guides/release`)
- `https://guides.emberjs.com/v3.16.0/ember-inspector/deprecations/` (for `guides/v3.16.0`)

**Comment by ijlee2** [comment]
cc @jenweber @locks

**Comment by geneukum** [comment]
Thanks, @ijlee2! I have opened the PR: https://github.com/ember-learn/guides-source/pull/1809 for the Learning Team to review.
