### ISSUE TITLE
Create a Additional Testing Tools Page

### ISSUE THREAD

**Issue by rohan09-raj** [ember-learn/guides-source#1808]
- Task is to move the `What tools can help me ?` section here, https://guides.emberjs.com/release/testing/ to a new section in the `Testing`.
![image](https://user-images.githubusercontent.com/78433013/163428714-daa1c544-53c9-4669-9393-b3c04e5f97e1.png)

- Create a new page in `Testing` named `Additional Testing Tools` and move the above-mentioned content from the `Introduction` to that new page.

**Comment by jenweber** [comment]
Some tips for how to create this new page:
- Only make changes to the files in the `release` directory. Don't worry about older versions
- Add the file to pages.yml and create the markdown file. Then it should show up in the app.

**Comment by rohan09-raj** [comment]
Can I work on this issue ??

**Comment by rohan09-raj** [comment]
@jenweber I have worked with several features in EmberJS staying in Real Dev Squad community. I would like contribute for improving the ember docs as well. Can you please assign this task to me ?

**Comment by jenweber** [comment]
Just assigned you, thanks for your help!

**Comment by jenweber** [comment]
Closed by #1810 🎉
