### ISSUE TITLE
Improve Explanation on Action Binding in the Input Helpers Section

### ISSUE THREAD

**Issue by jayjayjpg** [ember-learn/guides-source#181]
## Current Behaviour

The [Input Helper Section](https://guides.emberjs.com/v3.4.0/templates/input-helpers/) on the Guides highlights how different types of the `input` helper can be used.
When reviewing the section on how to bind actions to the `{{input}}` helper (https://guides.emberjs.com/v3.4.0/templates/input-helpers/#toc_actions), the following statement is made:

```Event Names must be dasherized.```

<img width="805" alt="capture d ecran 2018-10-03 a 00 22 42" src="https://user-images.githubusercontent.com/8811742/46380494-c19b9280-c6a2-11e8-9ca5-6238d5021505.png">

This is in fact only true for the `{{input}}` helper with the `type="text"`. This input helper requires the dasherized event name to be used to attach any actions:

```
{{input type="text" focus-in=(action "highlightUser")}}
```

Other types of input helpers which do not rely on the `TextSupport` Mixin do not own any dasherized event name API and actions can only be attached to their respective event handlers via the camelizedSyntax (e.g. `focusIn`). An example for a kind of input helper which does not own any functionality of the `TextSupport` Mixin is the one with `type="checkbox"`. For this, you can only attach actions as follows:

```
{{input type="checkbox" focusIn=(action "highlightUser")}}
```

Please also review [this stellar outline of the differences between both these uses in this issue](https://github.com/emberjs/ember.js/issues/16171).

## Expected Behaviour

The section describing actions used with the `{{input}}` helper should explicitly describe which type of input helper will require which type of event name wording (dasherized vs. camelized). Preferrably, this section should highlight a table of all input helper types available and their corresponding event name style.

Please find out which input helpers / text area helpers are based on the [`TextSupport` mixin](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/views/lib/mixins/text_support.js) and list those together with the dasherized version of viable event names. All other input / text helper types should be listed together with the camelized version of the viable event names.

## Implementation

Please update the Guides Source not only for the latest release `3.4`, but for any other preceding versions which include the statement about dasherized event names.

## Sources
- Guides Section on Actions Used With the Input Helper: https://guides.emberjs.com/v2.18.0/templates/input-helpers/#toc_actions
- Original Issue about Discrepancy between `{{input type="text}}` and `{{input type="checkbox"}}` regarding action binding: https://github.com/emberjs/ember.js/issues/16171
- Ember Twiddle Demo from the Original Issue: https://ember-twiddle.com/6f82aa1cce20e0831e285c172ca7e998
- Documentation on the Text Support Mixin: https://www.emberjs.com/api/ember/release/classes/Ember.TextSupport

**Comment by Parrryy** [comment]
I'd be happy to have a look at this 👍 If that's cool?

**Comment by jessica-jordan** [comment]
That sounds great :sparkles: Feel free to ping me if there are any questions anytime!

**Comment by gabrielgrant** [comment]
Thanks for tackling this folks :heart: 

Seems like ideally this would just be consistent in the API, but at least having it clear in the docs would be a big step forward, and would have saved me a good bit of head-scratching

**Comment by efx** [comment]
@Parrryy any progress? Feel free to ping me on ember discord for any help.

**Comment by Parrryy** [comment]
@efx I had to leave the country for a few weeks on short notice, I've returned and will continue this today.

**Comment by locks** [comment]
Closing as no longer relevant. Thanks everyone for the discussion!
