### ISSUE TITLE
Discussion: rename Ember Data to ember-data in the guides?

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#184]
In #165, @runspired suggests that some learning confusion stems from people not understanding that Ember Data is a library within the ember ecosystem. Chris suggests that calling it ember-data might help.

I would like to discuss the pros and cons and decide if we will do the renaming.

Pros:
- clearer indicators that ember data has its own API
- improved mental model of the Ember ecosystem

Cons
- Any SEO concerns?
- Any search concerns?
- Work to change across ember-cli, ember-data, ember.js, and other relevant libraries

Open questions
- would we retroactively update blog posts?

I’m in favor of renaming, but let’s chat.

Edit: I should also mention that the Ember Data team needs to confirm their use of the terminology too.

**Comment by locks** [comment]
If we are changing this decision, we need to update ember-cli, ember-data, ember.js, and other relevant libraries that we might mention.

**Comment by locks** [comment]
Do we retro-update blog posts as well?

**Comment by jenweber** [comment]
I added these to the pros/cons list.

I would say that no, we do not retro update blog posts. They are moments in time that we do not maintain for accuracy, generally speaking.

**Comment by mansona** [comment]
I will add my opinion on a case by case basis to each of your points: 

> Any SEO concerns?

If we're only changing Ember Data to ember-data then it is unlikely going to make any difference to SEO for either Ember or ember-data. Of course we would need to do some specific research into how Google tokenises our content and exactly what base word ember-data would boil down to. Currently, I think our *SEO juice* will just be going to the word Ember in if we're using `Ember Data`

> Any search concerns?
If by search you mean Algolia search then this will have **no effect** all `ember-data` results will come back if you search without the hyphen. It is likely that they are ignoring it in their tokenisation process 👍 

> Work to change across ember-cli, ember-data, ember.js, and other relevant libraries
I am happy to do this with things like ember-cli and ember-data but we need to be **very careful** when it comes to changing Ember to Ember.js. Google **does** consider Ember.js different to Ember so we are effectively "splitting the vote" right now. This is a wider SEO concern that should not block your current efforts so for the meantime we should not update/change `Ember.js` in my opinion.

> would we retroactively update blog posts?
Yes 😂I think we need to be very consistent for these things and if we're aiming for a less confusing situation we can't just keep things "consistent for all future content" assuming that nobody will come across any older content. I am very ok with rewriting history to make older docs/content more understandable and it's one of the reasons why I'm working on infrastructure to make this sort of stuff more possible in the future 👍 

Overall I'm a strong 👍on this idea overall 🎉

**Comment by MelSumner** [comment]
I believe this provides sufficient clarification:

![image](https://user-images.githubusercontent.com/4587451/62478986-16e87a80-b772-11e9-897a-1cdcc2da36f1.png)
 



If any further changes are requested, I strongly suggest we engage in A/B testing before making any decisions.

**Comment by locks** [comment]
Renamed to EmberData.
