### ISSUE TITLE
Can not sign up for map-box without a credit card anymore

### ISSUE THREAD

**Issue by Damans227** [ember-learn/guides-source#1840]
For the super-rentals tutorial documentation available here:

[Managing Application-level Configurations](https://guides.emberjs.com/release/tutorial/part-1/reusable-components/#toc_managing-application-level-configurations)

A credit card is now required to sign up for the `Map-Box API` and it seems you can't do it without one. You can pay through Stripe by clicking the map-box link in the `Ember-Js` documentation. Here is a screen shot: 

![mapbox_error](https://user-images.githubusercontent.com/61474540/185764883-a9803599-b0b3-44ea-a11d-b8aeb32476e1.png)

Therefore, the following line in the documentation is no longer valid: 

```
We will use the [Mapbox](https://www.mapbox.com/) API to generate maps for our rental properties. You can [sign up](https://www.mapbox.com/signup/) for free and without a credit card.
```

**Comment by MinThaMie** [comment]
Close this in favor of #1938 because it has more information about a way forward
