### ISSUE TITLE
run-loop information needs to be updated

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#187]
As per https://github.com/rwjblue/rfcs/blob/embrace-the-autorun/text/0000-remove-autorun-assertion.md  the guide content needs to be updated to reflect the current reality of the run-loop. 

- [ ] review the guides for mention of run-wrapping, and remove them. 
- [ ] update the [run-loop guide](https://guides.emberjs.com/v2.18.0/applications/run-loop/):
  - [ ] change the verbiage that mentions the reasoning for the autorun assertion
  - [ ] remove instructions to `Ember.run` wrap things

**Comment by sivakumar-kailasam** [comment]
@gokatz this might interest you 🙂

**Comment by gokatz** [comment]
Yes, it is 😸 
Will revamp those sections

**Comment by locks** [comment]
PR is merged!
