### ISSUE TITLE
Update guides-source to 3.28

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-source#1920]
In the https://github.com/ember-learn/guides-source/pull/1717 PR we need to update to ember 3.28 before the new design template can work (that's the oldest supported version)

It would be great if we didn't have the Ember update as part of that PR because it's already going to be reasonably big. Don't spend too much time on this because we can just leave the update in the redesign branch if it will be too hard 👍 

note: I updated using ember-cli-update so that we can get the blueprint updates too 👍

**Comment by jaredgalanis** [comment]
tried this, but it's not passing yet and haven't had more time to investigate: https://github.com/ember-learn/guides-source/pull/1925

**Comment by MinThaMie** [comment]
During the meeting on the 29th we decided to go with the update that is already in the branch
