### ISSUE TITLE
Don't teach jQuery APIs

### ISSUE THREAD

**Issue by simonihmig** [ember-learn/guides-source#194]
While I think most guides content teaches native DOM APIs for good reasons, the [component lifecycle guide](https://github.com/ember-learn/guides-source/blob/master/guides/v3.4.0/components/the-component-lifecycle.md) still references jQuery APIs. 

I believe this should be updated, as per [RFC294](https://emberjs.github.io/rfcs/0294-optional-jquery.html) (even more so with [RFC386](https://github.com/emberjs/rfcs/pull/386), should this be accepted), to prevent "accidental" use of jQuery.

**Comment by jelhan** [comment]
Fixed by #200, isn't it?

**Comment by simonihmig** [comment]
@jelhan Yes, indeed! Thanks for mentioning!
