### ISSUE TITLE
Seems NASA is not using ember.js and so ember inspector won't detect it

### ISSUE THREAD

**Issue by xnivaxhzne** [ember-learn/guides-source#1982]
In [this section](https://guides.emberjs.com/release/getting-started/#toc_what-is-ember), it is mentioned that
```
A browser extension, or bookmarklet, to inspect your application live. It's also useful for spotting Ember applications in the wild, try to install it and open up the [NASA website](https://www.nasa.gov/)!
```
But it turns out that NASA is not using ember anymore. If so, can we change the text accordingly?

**Comment by IgnaceMaes** [comment]
Good spot, it looks like the website did indeed change.

A safe bet would be to adjust the text to refer to the current docs site. We'll know for sure that stays an Ember app!

**Comment by NullVoxPopuli** [comment]
looks like NASA is just using WordPress now 😅

**Comment by IgnaceMaes** [comment]
Fixed by https://github.com/ember-learn/guides-source/pull/2041.
