### ISSUE TITLE
import { inject } vs import { service }

### ISSUE THREAD

**Issue by rgaiacs** [ember-learn/guides-source#2004]
https://guides.emberjs.com/release/applications/dependency-injection/#toc_ad-hoc-injections says

> Dependency injections can also be declared directly on Ember classes using inject. Currently, inject supports injecting controllers (via import { inject } from '@ember/controller';) and services (via import { inject } from '@ember/service';).

but the example uses `import { service } from '@ember/service';`

Can I have a clarification of `import { inject }` vs `import { service }`?

**Comment by NullVoxPopuli** [comment]
The docs need updated (simply for consistency and less typing), service should be preferred, tho my RFC to deprecate inject is low priority atm.

https://github.com/emberjs/rfcs/pull/1001

**Comment by IgnaceMaes** [comment]
Importing as `service` is indeed preferred.

It was adjusted in the code examples (see https://github.com/ember-learn/guides-source/pull/1766). But it looks like this usage was over. A PR to change it would be appreciated!

**Comment by rgaiacs** [comment]
Thanks for the clarification! https://github.com/ember-learn/guides-source/pull/1766 looks good to me. I will close this.
