### ISSUE TITLE
NASA website doesn't appear to be an Ember app

### ISSUE THREAD

**Issue by kategengler** [ember-learn/guides-source#2033]
https://github.com/ember-learn/guides-source/blob/master/guides/release/getting-started/index.md

https://guides.emberjs.com/release/getting-started/

says 

> [Ember Inspector](https://guides.emberjs.com/release/ember-inspector/) - A browser extension, or bookmarklet, to inspect your application live. It's also useful for spotting Ember applications in the wild, try to install it and open up the [NASA website](https://www.nasa.gov/)!

but the NASA site no longer appears to be an Ember app. We should replace this.

**Comment by IgnaceMaes** [comment]
Fixed by https://github.com/ember-learn/guides-source/pull/2041
