### ISSUE TITLE
Diff in example is not working

### ISSUE THREAD

**Issue by rgaiacs** [ember-learn/guides-source#2035]
In https://guides.emberjs.com/release/components/template-lifecycle-dom-and-modifiers/, we have

![Screenshot 2024-06-18 at 15-18-08 Template Lifecycle DO](https://github.com/ember-learn/guides-source/assets/1506457/123fd4c5-ceba-4c42-8d17-25c11714ba4c)

The code source is

``````
First, we add actions to handle the `click` events for the `Play` and `Pause` buttons:

```handlebars {data-filename="app/components/audio-player.hbs" data-diff="-3,+4,-5,+6"}
<audio src={{@srcURL}} />

<button type="button">Play</button>
<button type="button" {{on "click" this.play}}>Play</button>
<button type="button">Pause</button>
<button type="button" {{on "click" this.pause}}>Pause</button>
```
``````

The `data-diff` is not working.

**Comment by IgnaceMaes** [comment]
Looks okay on my end.

<img width="835" alt="image" src="https://github.com/ember-learn/guides-source/assets/10243652/6fc627f9-fc8e-49bc-a674-1bfc612b2bd7">

Is that a screenshot from the live version, or a local one? The filename is off in yours too, as it contains quotes.

If it's the live version, can you provide more details like browser version and OS to reproduce this on?

**Comment by rgaiacs** [comment]
Dear @IgnaceMaes, Thanks for the reply.

> Is that a screenshot from the live version, or a local one?

Live version with Firefox. Unfortunately, I cannot reproduce now.

# Firefox

Version 127.0 (64-bit)

OS: Windows 10 Enterprise

OS Version: 22H2

OS Build: 19045.4529

Now, It looks good as in the screenshot on https://github.com/ember-learn/guides-source/issues/2035#issuecomment-2176695666.

# Google Chrome

Version 125.0.6422.176 (Official Build) (64-bit)

OS: Windows 10 Enterprise

OS Version: 22H2

OS Build: 19045.4529

It looks good as in the screenshot on https://github.com/ember-learn/guides-source/issues/2035#issuecomment-2176695666.
