### ISSUE TITLE
Switch to `pnpm` as package manager

### ISSUE THREAD

**Issue by IgnaceMaes** [ember-learn/guides-source#2049]
This would align the repo with other modern Ember repos.

Steps:
1. Import lockfile: https://pnpm.io/cli/import/
2. Update Actions CI
3. Define correct versions in `package.json`

**Comment by balinterdi** [comment]
@IgnaceMaes I think this was fixed in #2071 and thus can be closed.

**Comment by IgnaceMaes** [comment]
Indeed!

Closing 😄
