### ISSUE TITLE
Create an async/await version of the complex component sections of Super Rentals

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/guides-source#228]
Currently the [complex component](https://guides.emberjs.com/release/tutorial/autocomplete-component/) section of Super Rentals features an asynchronous search.  

There is some code there to ensure search requests and responses do not get out of sync, and it is not ideal for new learners.

What I'd like to do is take advantage of async await in this code, which would simplify it, as well as show learners that its a valid option within ember.

**Comment by locks** [comment]
No longer applies due to re-written Super Rentals!
