### ISSUE TITLE
Documentation audit for array-helper feature flag

### ISSUE THREAD

**Issue by tomdale** [ember-learn/guides-source#238]
We would like to "go" the [array-helper feature flag](https://github.com/emberjs/ember.js/pull/17054) that landed in canary.

We would like to request a Learning Team audit of the API docs as implemented today, as well as thoughts on whether the guides should be updated to cover this functionality.

**Comment by locks** [comment]
The documentation is already written at https://github.com/ember-learn/guides-source/pull/212.

**Comment by jenweber** [comment]
closed by https://github.com/ember-learn/guides-source/pull/177

It's in the guides as of the launch of 3.6 🎉
