### ISSUE TITLE
Documentation audit for glimmer-modifier-manager feature flag

### ISSUE THREAD

**Issue by tomdale** [ember-learn/guides-source#239]
We would like to "go" the [glimmer-modifier-manager feature flag](https://github.com/emberjs/ember.js/pull/17143) that landed in canary.

We would like to request a Learning Team audit of the API docs as implemented today, as well as thoughts on whether the guides should be updated to cover this functionality.

**Comment by locks** [comment]
As implemented today, the Guides do not cover this sort of documentation.
There's some efforts underway to explore how to diversify the kinds of documentations we officially provide.
