### ISSUE TITLE
`didUpdateAttrs` when service property change

### ISSUE THREAD

**Issue by ppcano** [ember-learn/guides-source#244]
In the following example, if `popup.foo` changes, the `didUpdateAttrs` hook will not be fire: 
```
export default Component.extend({
  popup: service(),
  foo: oneWay('popup.foo')
```

Initially, I was expecting that a change on  `popup.foo` (a component attribute/property in my mind) will fire the `didUpdateAttrs` hook, but it will not. The guide describes it:

[Resetting Presentation State on Attribute Change with `didUpdateAttrs`](https://guides.emberjs.com/release/components/the-component-lifecycle/#toc_resetting-presentation-state-on-attribute-change-with-didupdateattrs)

> `didUpdateAttrs` runs when the attributes of a component have changed, but not when the component is re-rendered, via `component.rerender`, `component.set`, or changes in models or services used by the template.

Because of the initial confusion, I wonder if it may be good to explain this particular more clearly.

**Comment by locks** [comment]
Can you give it a go? The trick here is that `popup` didn't change, it's still pointing to the same object. The same happens with arrays!

**Comment by ppcano** [comment]
I thought the trick was that the attribute must be passed via the component invocation?

```
<MyComponent @foo=popup.foo />
```

Note, I haven't tested this in a long time.

**Comment by locks** [comment]
@ppcano yeah, that would work because the `foo` would then change. A nitpick, don't forget you need to wrap dynamic values in mustaches:  `<MyComponent @foo={{popup.foo}} />`

**Comment by locks** [comment]
This section is gone, so the issue is no longer relevant 😅
