### ISSUE TITLE
List of tiny tutorial fixes that should happen

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#245]
To help with one of these issues, please open a separate issue for it and put the changes in its own PR. This is a list of things I noticed while reading the tutorial from start to finish:

## Volunteer needed
- [ ] "Creating your app" should have a quick note about the kind of knowledge prerequisites that are helpful (not required)
- [x] backslash typo, `for short/` is in `routes-and-templates.md`
- [ ] "functions that are invoked `automatically when a route is rendered`"
- [ ] "To keep things simple at first, we'll populate the model for our rental listing page to use a hard-coded array of JavaScript objects." is wordy
- [ ] "client HTTP stubbing library" will be confusing to new devs. Could be improved by saying immediately that "What this means is Mirage will allow us to create fake data..."
- [ ] "In order for this to work, we need our application to default to making requests to the namespace of /api" could be stated more plainly
- [ ] "Let's call this action toggleImageSize" block breaks the app, since the action is not defined. Needs a note that for the next step to work, we need to make changes in both the js and hbs file
- [ ] needs an explanation of when to make a helper instead of a component
- [ ] needs a quick explanation of the difference between guides and API docs
- [ ] "using ember data" should briefly explain how the ember data model and the model hook are different, or maybe link to that explanation in the guides
- [ ] "An Ember Service is an object that can be made available for different parts of an application." does not differentiate from components. Should indicate that it's special because there is only one instance of it, and it can be used almost anywhere to store shared information or methods.
- [ ] "3rd party map API" should prob be "third-party" and we should explain what is meant by that term

## Done
- [x] linting -  Unnecessary string concatenation. Use {{rental.image}} instead of "{{rental.image}}"
- [x] "Building a Simple Component" page needs a definition of what a component is, and its relationship to routes #simple
- [x] Needs plainer words - "Here we invoke the rental-listing component by name, and assign each rentalUnit as the rental attribute of the component."
- [x] "The value of isWide comes from our component's JavaScript file" should be followed with a statement like "any attributes in the component's JavaScript file can be used in its template"
- [x] "Be sure to restart your server after the addon has installed successfully." should tell them how to stop the server, control-c #282 
- [x] Handlebars are not explained, in general https://github.com/ember-learn/guides-source/pull/291#pullrequestreview-180530621
- [x] "All we want to do when a user..." section provides too much info. Should just introduce the hook and replaceWith. 
- [x] When the application.hbs is introduced, it should have a note about how whatever is there will show up on any page in the app
- [x] Tutorial could be improved with a short explanation that a route's template and js file can "talk" to each other #291 

Higher level observations, not ready to be PR'd:
- Components should come before mirage/Ember Data
- We aren't really teaching the mental model well of which files talk to each other, or the concept of passing data
- "Building a Complex Component" really should just show a computed property and an input, IMO. Ideally it would come after services, but that refactor is a pain.

**Comment by toddjordan** [comment]
linting fixes included with the maps pr

**Comment by zachgarwood** [comment]
@jenweber Would you please specify where you encountered this item:
> backslash typo, for short/

**Comment by zachgarwood** [comment]
@jenweber what is the context for this item:
> * needs a quick explanation of the difference between guides and API docs

Where should this explanation live?

**Comment by jenweber** [comment]
> needs a quick explanation of the difference between guides and API docs

@zachgarwood I am not sure. All I know is that when I started learning Ember, I thought the Guides were all that there was and didn't understand when to look at the API docs. For someone where it's their first framework, this is probably common.

> backslash typo, for short/

This is in `routes-and-templates.md`

_Now run `ember serve` (or `ember server`, or even `ember s` for short/) on your command line to start
the Ember development server and then go to [`http://localhost:4200/about`](http://localhost:4200/about/) to
see our new page in action!_

**Comment by jenweber** [comment]
Thanks everyone who helped with this issue back in the day! I think we hit all the major points. Closed.
