### ISSUE TITLE
htmlSafe link in Guides links to an empty class page

### ISSUE THREAD

**Issue by jaredgalanis** [ember-learn/guides-source#248]
htmlSafe link in [Guides for Templates / Writing Helpers](https://guides.emberjs.com/release/templates/writing-helpers/) links to [an empty class page](https://www.emberjs.com/api/ember/release/classes/@ember%2Fstring/methods/htmlSafe?anchor=htmlSafe).

Seems like it should link [here](https://www.emberjs.com/api/ember/3.5/functions/@ember%2Ftemplate/htmlSafe).

**Comment by cah-danmonroe** [comment]
Both htmlSafe links work for me.  Can probably close this issue.

**Comment by jenweber** [comment]
This was likely due to the fact that the API documentation page itself was missing in a particular release. Seems fixed now! Closed.
