### ISSUE TITLE
Add Tutorial Sub-Section: Converting handlebars component to angle brackets

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#250]
## To-Do
- [ ] add tutorial on converting a handlebars component to an angle bracket component

## Supporting Resources
- Video: [Angle Bracket Component Invocation in Ember.js](https://www.youtube.com/watch?v=KP_3MJTMpXI)
- Video: [Template-only components in Ember.js](https://www.youtube.com/watch?v=2DzV_0NAiUM)

**Comment by cah-danmonroe** [comment]
Even though I have started conversion with PR #292 we DO need a section on how to convert handlebars to angle brackets.

**Comment by locks** [comment]
Is this https://guides.emberjs.com/release/reference/syntax-conversion-guide/ ?

**Comment by jenweber** [comment]
Closed by the Syntax Conversion Guide

**Comment by jenweber** [comment]
Thanks everyone!
