### ISSUE TITLE
Analyze Section: Testing

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#251]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Section to review: 
[Testing](https://guides.emberjs.com/release/testing/)

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by cah-danmonroe** [comment]
Just a reminder that I have already submitted a PR #292 where I have already converted the 3.6 documentation to angle brackets. I can address further  #issues from there.

**Comment by locks** [comment]
I need someone knowledgeable about testing to cover this section.

**Comment by Gaurav0** [comment]
This section is already pretty up to date, looks like someone went over it recently with the RFC-232 changes. Some notes:

There is no explanation for why the types of tests introduced in the guides go in directories with legacy names (acceptance, integration). There is no explanation of why both Unit Tests and Container Tests both go in the unit directory.

It's weird how Application Tests come first, I would put them last, or at least after Testing Basics.

There are no examples of nesting modules. (A module within a module).

There is no explanation of how to stub/mock a method or object in a unit or container test.

There is no mention of ember-cli-mirage or how to mock ajax requests.

Testing routes should discuss how to handle testing the asynchronous beforeModel, model, or afterModel hooks.

Maybe discuss the following:

Testing Query Params?

Testing Native ES Classes?

Testing ember-concurrency tasks or methods using async/await?

What to do if you get the "autorun is disabled, wrap in a run loop" error message?

**Comment by MelSumner** [comment]
Thank you @Gaurav0!! I've captured this in https://github.com/ember-learn/guides-source/issues/458
