### ISSUE TITLE
Analyze Section: Routing

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#253]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Section to review: 
[Routing](https://guides.emberjs.com/release/routing/)

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by locks** [comment]
## Defining your routes

Update `{{link-to}}`.

## Specifying a route's model

Update for Octane layout.
Update for native classes.
Update `{{link-to}}`.

## Rendering a template

Update for Octane layout.
Update for native classes.

## Redirecting

Update for Octane layout.
Update for native classes.

## Preventing and retrying transitions

Update for Octane layout.
Update for native classes.
Update `{{link-to}}`.

## Query parameters

Update for Octane layout.
Update for native classes.
Update `{{link-to}}`.

## Asynchronous Routing

Update for Octane layout.
Update for native classes.

**Comment by MelSumner** [comment]
@locks I'm a little confused about this comment- can you clarify? Are you saying that all of these things need separate issues so they can be re-written?

**Comment by locks** [comment]
I think that since the work should be relatively straightforward conversions that they can be lumped together.
Filed the relevant issue at https://github.com/ember-learn/guides-source/issues/438.
