### ISSUE TITLE
Analyze Section: Ember Inspector

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#257]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
[Ember Inspector](https://guides.emberjs.com/release/ember-inspector/)

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by locks** [comment]
## Introduction

Update for angle bracket.
Update for Octane layout file paths.
Update for native class.
Update Slack mention to Discuss/Discord.

## Object Inspector

Update for angle bracket.
Update for Octane layout file paths.
Update for native class.

## Component Tree

Update for angle bracket.
Update for Octane layout file paths.
Update for native class.

## The view tree

Update for angle bracket.
Update for Octane layout file paths.
Update for native class.
Update for Inspector with Components panel.

## Inspecting Routes

Update for Octane layout file paths.
Update for Inspector with Components panel.

## Data Tab

Update for Octane layout file paths.
Update for native class.

## Tackling Deprecations

Update for Octane layout file paths.

## Debugging Promises

Update for native classes and Promises, possibly?
