### ISSUE TITLE
Analyze Section: Controllers

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#258]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
[Controllers](https://guides.emberjs.com/release/controllers/)

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by locks** [comment]
Conceptually, there are no changes necessary to this section.

**Comment by locks** [comment]
https://github.com/ember-learn/guides-source/issues/433
