### ISSUE TITLE
Analyze Section: Contributing to Ember.js- Adding New Features

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#259]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
[Contributing to Ember.js- Adding New Features](https://guides.emberjs.com/release/contributing/adding-new-features/)

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by locks** [comment]
No related changes necessary.
