### ISSUE TITLE
Analyze Section: Configuring Ember

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#260]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
Configuring Ember

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by locks** [comment]
## Disabling Prototype Extensions

I need some help confirming what is going to happen in this area.

## Optional Features

We will be flipping some of these values, we might need to document that here.

## Debugging

Update for native classes.
Update for runloop changes. (?)
We should consider removing this guide and pointing to Ember Inspector instead.

**Comment by locks** [comment]
https://github.com/ember-learn/guides-source/issues/439
https://github.com/ember-learn/guides-source/issues/440

**Comment by tomdale** [comment]
@locks Can we also get an issue to make sure we move the guides away from using prototype extensions? These cause a lot of problems in FastBoot environments, where objects cross realms.

**Comment by MelSumner** [comment]
https://github.com/ember-learn/guides-source/issues/532 will address this. thanks @tomdale :+1:
