### ISSUE TITLE
Analyze Section: Components - Block Params

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#268]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
Components - Block Params

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by gossi** [comment]
Yesterday I realized `(has-block-params)` is missing in this section. I've filed this ~a year ago: https://github.com/emberjs/guides/issues/2135

Also the order of if statements in the template is important. It must be this way:

```hbs
{{#if (has-block-params)}}
  block + block-params
{{else if (has-block)}}
  just block
{{else}
  inline
{{/if}}
```

**Comment by cah-danmonroe** [comment]
Just a reminder that I have already submitted a PR #292 where I have already converted the 3.6 documentation to angle brackets. I can address further  #issues from there.

**Comment by locks** [comment]
Addressed by https://github.com/ember-learn/guides-source/pull/292.

@gossi I am closing this issue as that specific concern is unrelated to Octane/new component syntax. Can you open a separate issue in this repository?

**Comment by gossi** [comment]
Erm maybe I missunderstand this. But PR #292 hasn't covered `(has-block-params)` yet and yes this issue is unrelated to Octane but applies to the current ember version/guides, which this issue is about - so I am confused now, why I should open another ticket, which would just be a clone of that.

**Comment by locks** [comment]
https://github.com/ember-learn/guides-source/issues/441
