### ISSUE TITLE
Analyze Section: Addons and Dependencies

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#274]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
Addons and Dependencies: Managing Dependencies

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by cah-danmonroe** [comment]
Just a reminder that I have already submitted a PR #292 where I have already converted the 3.6 documentation to angle brackets. I can address further  #issues from there.

**Comment by locks** [comment]
I believe this needs to be updated to cover some of the more recent developments in the ecosystem, but unrelated to Octane.
