### ISSUE TITLE
Analyze Section: Getting Started

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#275]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Section to review: 
Getting Started (index page)

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by cah-danmonroe** [comment]
Just a reminder that I have already submitted a PR https://github.com/ember-learn/guides-source/pull/292 where I have already converted the 3.6 documentation to angle brackets.

**Comment by locks** [comment]
No changes required.
