### ISSUE TITLE
Analyze Section: Getting Started - JS Primer

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#276]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
JS Primer

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue.

**Comment by jaredgalanis** [comment]
@MelSumner happy to help out with this one since I was involved in the prior iteration of the primer, if that's helpful.

**Comment by cah-danmonroe** [comment]
Just a reminder that I have already submitted a PR #292 where I have already converted the 3.6 documentation to angle brackets. I can address further  #issues from there.

**Comment by locks** [comment]
Since this guide only addresses vanilla JavaScript, there are no changes necessary.
@jaredgalanis we can keep working on improving it!
