### ISSUE TITLE
Analyze Section: Getting Started- Core Concepts

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#278]
## Intro
This is part of a larger project that reviews the guide content to determine what, if any, updates need to be added to the guides as angle bracket and/or template-only components become the standard. 

## Sub-section to review: 
Core Concepts

## Primary goals: 
- [ ] Review this sub-section: what needs to be updated for the new standards?
- [ ] If analysis reveals that documentation is necessary, create a new issue with those tasks, and comment on this issue, linking to the new issue. 

## Resources
- Template only components RFC https://github.com/emberjs/rfcs/blob/master/text/0278-template-only-components.md
- Angle Brackets invocation RFC https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md

**Comment by cah-danmonroe** [comment]
Just a reminder that I have already submitted a PR #292 where I have already converted the 3.6 documentation to angle brackets. I can address further  #issues from there.

**Comment by locks** [comment]
https://github.com/ember-learn/guides-source/issues/434
