### ISSUE TITLE
tutorial/service.md wording discussion

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#300]
Sub issue of #245.
>  "An Ember Service is an object that can be made available for different parts of an application." does not differentiate from components. Should indicate that it's special because there is only one instance of it, and it can be used almost anywhere to store shared information or methods.

We define services here: https://github.com/ember-learn/guides-source/blob/master/guides/v3.5.0/applications/services.md.

The problematic, half-definition is given here: https://github.com/ember-learn/guides-source/blob/master/guides/v3.5.0/tutorial/service.md. 

# proposed solution / change
I think we should remove the line attempting to define a service in `tutorial/service.md` and simply link the prior line end `Ember services.` to applications/services.md. By linking we give the user a clear path to add services to their mental model and avoid the liability of competing definitions.

**Comment by locks** [comment]
@efx can you send a PR pliz?
