### ISSUE TITLE
header uses ES6 to describe modules, description leads with ES2015 modules

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#301]
ES2015 modules is certainly wordier, but more technically accurate. [The header](https://github.com/ember-learn/guides-source/blob/master/guides/v3.5.0/tutorial/ember-cli.md#es6-modules) says
> ES6 Modules

but the line after says

> ECMAScript 2015 (ES2015 for short or previously known as ES6) modules 

To me, this arrangement of terms is distracting. 

# proposed change
I propose we make the header just `Modules`. This would be similar to [babel's documentation](https://babeljs.io/docs/en/learn#modules).

**Comment by locks** [comment]
Can you send a PR for this? 😁
