### ISSUE TITLE
Computed property dependencies

### ISSUE THREAD

**Issue by thec0keman** [ember-learn/guides-source#303]
The current description of computed property dependencies is helpful, though it would be helpful if they mentioned the use of `.[]` and the difference between that and `@each.{}`

I've found [this](https://blog.eladshahar.com/performant-array-computed-properties.html) blog very helpful at summarizing these.

**Comment by locks** [comment]
I am closing this issue as both [When to use `[]` and `@each`](https://guides.emberjs.com/release/object-model/computed-properties-and-aggregate-data/#toc_when-to-use--and-each) and [`[]` vs `@each`](https://guides.emberjs.com/release/object-model/computed-properties-and-aggregate-data/#toc_-vs-each) should cover this.
Please re-open with more detail if you don't agree, thank you!
