### ISSUE TITLE
Broken link to RSVP in Building a Complex Component

### ISSUE THREAD

**Issue by maxcal** [ember-learn/guides-source#306]
guides/v3.5.0/tutorial/autocomplete-component.md contains a broken link to https://www.emberjs.com/api/ember/release/modules/rsvp.

Should this link point to the [ember api docs](https://www.emberjs.com/api/ember/release/classes/RSVP.Promise) or maybe the RSVP GitHub repo?

**Comment by locks** [comment]
Link is now working!
