### ISSUE TITLE
It's not obvious how to use query-params from the template/links section

### ISSUE THREAD

**Issue by sonic1981** [ember-learn/guides-source#310]
The [template/links](https://guides.emberjs.com/v3.4.0/templates/links/)/query-params section is a bit cryptic and doesn't show you how to set up query params. it needs a link to [query params section of route](https://guides.emberjs.com/v3.5.0/routing/query-params/)

I'd suggest adding something along the lines of:

`For more information on how to use query parameters see the [query parameters](../../routing/query-params/) section in Routing.`

I'm happy to do this if people agree?

**Comment by jenweber** [comment]
Sorry to not respond sooner. We only manage to review Issues/PRs every few days but this is a great idea and we appreciate the help! 

Closed by #311, thanks!

**Comment by sonic1981** [comment]
@jenweber  No worries! This was plenty fast enough! :)
