### ISSUE TITLE
Update "Managing Dependencies"

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#320]
## Goal
Update the Addons and Dependencies/Managing Dependencies sub-section of the Ember Guides. (https://guides.emberjs.com/release/addons-and-dependencies/managing-dependencies/) 

## To Do
- [x] Expand the Addons section by adding 2-3 paragraphs that explain more about the addon ecosystem, and maybe expound on what ember observer is, and what you can expect to find there. 
- [x] Update the explanation for `ember-auto-import` to the "regular npm packages" section

**Comment by Turbo87** [comment]
@locks with all this keep in mind that `ember-auto-import` does not compile dependencies with Babel, so if they are incompatible with your browser targets you're out of luck (see https://github.com/ef4/ember-auto-import/issues/41)

**Comment by pablobm** [comment]
@locks - I believe the first of the two checkboxes can be ticked as per https://github.com/ember-learn/guides-source/pull/326

**Comment by acorncom** [comment]
thanks @pablobm. @locks anything else we want to do here?
