### ISSUE TITLE
incorrect comment about jQuery.ajax returning a Promise

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#33]
The  [async routing section on promises](https://guides.emberjs.com/v3.1.0/routing/asynchronous-routing/#toc_a-word-on-promises) has a comment that states:

> Note: jQuery AJAX methods return promises

This is incorrect. The[ jQuery API](http://api.jquery.com/jQuery.getJSON/) indicates `$.getJSON` and other low level methods return the `jqXHR` [type](http://api.jquery.com/Types/#jqXHR). I think the code in this example should be updated with a modern example. This would avoid the overhead of teaching the potentially confusing history and semantics behind jQuery's request utilities.

**Comment by sivakumar-kailasam** [comment]
Thanks for reporting this. Here's a comment from their [api docs](http://api.jquery.com/jQuery.getJSON/),
> This jQuery XHR object, or "jqXHR," returned by $.getJSON() implements the Promise interface, giving it all the properties, methods, and behavior of a Promise.

We might have avoided mentioning the jqXHR object to avoid explaining the intricacies of jqXHR when we originally wrote that code block back in 1.x series of the guides. 

Closing this issue for now. Please feel free to open a separate issue/PR about modernizing it.
