### ISSUE TITLE
Markdown link inconsistencies

### ISSUE THREAD

**Issue by maxwondercorn** [ember-learn/guides-source#330]
Since working on the linting and spellchecking improvements, I've noticed that the guides are inconsistent on how markdown links are created.

In the cli-guides, there are all inline `[link name](https://somelink...)` and the guides-source has a mix between inline and keyed links.  In some cases within the same file.  Not sure about other docs.

Key links are in the markdown and the links defined at the bottom of the file

```
[My Link][]

[My Link]: http://www.myspeciallink.com
```

This came about from having different contributors working on the guides.  I raise the question should the format be standardized and the guides refactored to match?

While I normally use inline links in my markdown, the use of keys in large document sets has advantages.

- They improve markdown readability, which makes reviewing PRs easier because the text isn't interrupted by URLs
- If you use the same link multiple times in a document, you only have to define it in one location
- Improves maintainability. If a link needs to be updated, there is only one place to look.  Each document needs to be to visited, but you don't have to search through the document

There are probably more benefits  that I'm missing. The Remark linters will flag keys without a definition, so editing errors will be caught. Dead links are still an issue but I believe @mansona is working a solution for that.

**Comment by locks** [comment]
The team discussed this at one of the weekly meetings an decided that links should be inlined.
Can you help clean this up?

**Comment by maxwondercorn** [comment]
Yes I can work on it. Probably not until next week

**Comment by maxwondercorn** [comment]
I've started the links cleanup but will delay the PR until the octane guides preview is complete per a comment from @jenweber on ember-learn/cli-guides#101
