### ISSUE TITLE
Error substates

### ISSUE THREAD

**Issue by edeis53** [ember-learn/guides-source#335]
Is the documentation up-to-date for Error substates?
https://guides.emberjs.com/release/routing/loading-and-error-substates/#toc_error-substates

a 401 from our API returns the following in the error action:

```
code: undefined
description: undefined
errors: Array(1)
0: {status: "401", title: "The backend responded with an error", detail: "This resource is password protected"}
@each: (...)
[]: (...)
firstObject: (...)
hasArrayObservers: (...)
lastObject: (...)
length: 1
__proto__: Array(0)
fileName: undefined
isAdapterError: true
lineNumber: undefined
message: "Ember Data Request GET https:/foo a 401↵Payload (application/json)↵This resource is password protected"
name: "Error"
number: undefined
stack: "..."
```

There is no `error.status` property.

The only way to get the error is from the `error.errors` array.

```
  actions: {
    error: function(error, transition) {
      console.log(error.errors.firstObject);
      debugger;
   }
}
```

I'm a bit confused because this doesn't match the docs at all. Using the `JSONAPIAdapter` here.

**Comment by locks** [comment]
It should be up to date. Did you end up resolving this situation? It might be worth it to make a reproduction and post to the ember.js issue tracker.
