### ISSUE TITLE
Prefer `ember-cli` over `Ember CLI`

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-source#352]
I'm currently in the process of reviewing https://github.com/ember-learn/guides-app/pull/366 and I noticed on https://github.com/ember-learn/guides-source/blob/master/guides/v3.6.0/tutorial/ember-cli.md we have changed a use of `ember-cli` for `Ember CLI`. 

I am pretty sure this is part of the big "spellcheck" PR merge but I think we might have gone overboard on this one. I have a distant memory that we decided at some point to prefer dasherized lowercase names for **projects** that were independent npm packages 🤔 so use `ember-data` and `ember-cli` throughout the guides. 

Can someone on the @ember-learn/learning-team confirm this was indeed the decision and then we can continue with implementation to find and fix cases of this 👍

**Comment by kennethlarsen** [comment]
For the blog at least it's always `Ember CLI` (for Ember Times, release posts, even the category itself about Ember CLI). Not sure if that should be different for the guides?

**Comment by jelhan** [comment]
Please also note https://github.com/ember-learn/guides-source/issues/184 and https://github.com/ember-learn/cli-guides/issues/69. For CLI Guides it has been normalized to `Ember CLI` in https://github.com/ember-learn/cli-guides/pull/71.

**Comment by mansona** [comment]
Here is @locks's take on the issue: 

> our style guide is that we use the package name when we refer to the actual package such as "let's install the latest version of ember-cli" in page you linked but otherwise we should use the capitalized styling

which tallies with what we have discussed in the past. 

@jelhan if it is indeed being "normalised" we need to make sure that it is being used in the right context. If we have a rule in the new spellchecker then we probably need to remove that rule and go over all the cases that it has changed to make sure that it is correct 👍 

Also we should add the above (or something like it) to the **actual** styleguide here : https://github.com/ember-learn/guides-source/blob/master/CONTRIBUTING.md

**Comment by mansona** [comment]
@locks why was this closed? has it been fixed?

**Comment by locks** [comment]
@mansona as far as I could tell we do "Ember CLI" like is stated in the contributor styleguide!
