### ISSUE TITLE
[WIP] Add Accessibility Section

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#368]
While Accessibility isn't just an Ember concern, the guides should still identify best practices for Ember developers regarding accessibility. 

Potential Content: 
- [x] using the application wrapper (or not)
- [ ] focus considerations
- [ ] modal considerations
- [ ] custom component considerations
- [x] accessibility testing
- [x] addons that can help

**Comment by lifeart** [comment]
List of A11Y addons: https://github.com/ember-community-russia/awesome-ember/blob/master/README.md#a11y

**Comment by jenweber** [comment]
@MelSumner what do you think about closing this and spinning off new tickets with the details needed for remaining sections?

**Comment by MelSumner** [comment]
@jenweber I'm fine with that- we did the major work already.
