### ISSUE TITLE
Add an index page with a modified table of contents

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#388]
At the moment, `https://guides.ember.com` redirects to `/release`, which reflects the current stable release of Ember.
The goal would be that it instead renders a modified listing of the table of contents.

Tasks:
- [ ] Add new "Home" link to the Guides table of contents
- [ ] Implement page

note: more details incoming

**Comment by jenweber** [comment]
I think this can be closed since the new landing page has shipped. Feel free to reopen if you meant something else. Thanks!
