### ISSUE TITLE
Update Octane guides subsection - Components: creating a component

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#396]
## Goal
Update the "creating a component" sub-section of the Components section of the Octane guides so it includes how to do components in a way that is consistent with the Octane edition of Ember. 

## TODO
- [ ] write content for sub-section
- [ ] ensure code samples are included

## References
This issue is a part of the [Component section tracking issue](https://github.com/ember-learn/guides-source/issues/395)

**Comment by jenweber** [comment]
Covered by https://github.com/ember-learn/guides-source/blob/octane/guides/release/components/defining-a-component.md
