### ISSUE TITLE
Octane | Ember Inspector

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#427]
Outcome of https://github.com/ember-learn/guides-source/issues/257.

Most of the relevant content is inside screenshots, which will have to be updated as Ember Inspector is updated.

## The View Tree

This section is a legacy from previous Ember versions and should be removed.
I believe the Inspector team is working on incorporating features present in the View Tree into other parts of the extension.

## Library Info

This section still refers an `Ember` namespace API.
This should be updated for whatever API replaces it.

**Comment by rwwagner90** [comment]
We probably need to look through all of the guides and both update screenshots and language, etc.

**Comment by locks** [comment]
Being tracked at https://github.com/ember-learn/guides-source/issues/1406.
