### ISSUE TITLE
Update Octane guides subsection - Components: Nesting Components

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#428]
## Goal
Update the "Nesting Components" sub-section of the Components section of the Octane guides so it includes how to do components in a way that is consistent with the Octane edition of Ember. 

## TODO
- [x] write content for sub-section
- [x] ensure code samples are included

## References
This issue is a part of the [Component section tracking issue](https://github.com/ember-learn/guides-source/issues/395)

**Comment by ijlee2** [comment]
@MelSumner @locks I can help with this.

**Comment by ijlee2** [comment]
Upon discussion with the team, we thought a good place to add an explanation of Nested Components is https://octane-guides-preview.emberjs.com/release/components/defining-a-component/#toc_component-folder-structure . We will add a link to the API documentation https://api.emberjs.com/ember/release/classes/Component

**Comment by jenweber** [comment]
Closed by #909. Thanks Isaac!
