### ISSUE TITLE
 Update Octane guides section - Configuring Ember.js: Embedding Applications

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#439]
Your PR should target the `octane` branch.

## Goal
Update the "Embedding Applications" sub-section of the Octane guides so it is consistent with the Octane edition of Ember. 

## TODO
- [ ] Update code samples to native class and decorators
- [ ] Update code sample paths to Octane layout paths

**Comment by jenweber** [comment]
Closed, nothing to update here. The Router and Application are still the same in the blueprints.
