### ISSUE TITLE
 Update Octane guides section - Components: Using Block Params

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#441]
Your PR should target the `octane` branch.

## Goal
Update the "Using Block Params" sub-section of the Octane guides so it is consistent with the Octane edition of Ember. 

## TODO
- [ ] Update code samples to native class and decorators
- [ ] Update code sample paths to Octane layout paths

**Comment by gossi** [comment]
Do you trap yourself? #328

**Comment by locks** [comment]
@gossi I don't understand your question 🤔

**Comment by gossi** [comment]
Because you created another ticket just like this one. I don't understand why.

**Comment by locks** [comment]
#328 is to document `has-block-params`, this one is for the Octane preview Guides effort.

**Comment by jenweber** [comment]
Closed by work in https://github.com/ember-learn/guides-source/blob/octane/guides/release/components/wrapping-content-in-a-component.md
