### ISSUE TITLE
Update Octane guides section - Getting Started: Quick Start

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#444]
Your PR should target the `octane` branch.

## Goal
Update the "Quick Start" sub-section of the Octane guides so it is consistent with the Octane edition of Ember. 

## TODO
- [ ] Remove file and reference from table of contents
- [ ] Set up redirect to tutorials.emberjs.com

**Comment by wordofchristian** [comment]
Looking at this today

**Comment by locks** [comment]
Postponed pending discussion about per-edition tutorials.
