### ISSUE TITLE
Create new section & sub-section: Upgrading/editions

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#463]
Create a new section called "Upgrading" and add an "Editions" sub-section to it. 

Use the materials collected by @jenweber as the base, and build on top of that. 

Keep in mind that this should be tightly scoped to the section/sub-section and shouldn't include things that belong in other sections/sub-sections.

**Comment by jenweber** [comment]
Partially addressed by #515

**Comment by jenweber** [comment]
closed by #515 and pzuraq's work
