### ISSUE TITLE
Debugging guide should mention ember-cli-deprecation-workflow

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#475]
There is a section in the "Debugging" guide about "Dealing with deprecations".
It should reference back to https://guides.emberjs.com/release/configuring-ember/handling-deprecations/, which discusses how to use ember-cli-deprecation-workflow.

**Comment by rwjblue** [comment]
Thanks for creating the follow up issue for this! I'm happy to help someone if they have questions about how things should work...
