### ISSUE TITLE
Guides also have a few hiccups in IE11

### ISSUE THREAD

**Issue by lupestro** [ember-learn/guides-source#491]
The version drop-down isn't working at all in IE11. Loading the initial page, I saw `Object doesn't support property or method 'includes' ` so I suspect something, (maybe the select addon?) wasn't polyfilled during the build.

IE11 also had a little problem with the "Installing Ember" page. The URL path was "getting-started/" rather than "getting-started/something" (which seems suspicious anyway), but IE compounded the inconsistency by sticking "index" on the end of it, which resulted in a blank page - not a 404, but a blank, white page. This doesn't happen with other pages.

Because with that page, I still got the same exception when it loaded, it was obviously starting to do something. I suspect maybe it had trouble finding content for the false"index" page and displayed nothing instead.

So maybe there's an issue for handling of "missing content" as well that might extend beyond IE11. Not sure.

**Comment by locks** [comment]
This ship has sailed 😬 Hopefully it is no longer a problem!
