### ISSUE TITLE
Guides have a few hiccups with older versions of Edge.

### ISSUE THREAD

**Issue by lupestro** [ember-learn/guides-source#492]
With the Anniversary Edition of Windows 10, Edge doesn't display the dropdown of the version selector. Clicking the dropdown shows an empty list and the version appears as blank after that. Also, the black background for the example text isn't showing, making the examples hard to read. 

Both issues occur on:
```
Microsoft Edge 38.14393.2068.0
Microsoft EdgeHTML 14.14393
```

But it works in:
```
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
```

I dug around a little. While poised on object `ember619` - the article panel - the browser reports an unhandled exception `Object doesn't support property or method 'ToString'` in `didRender` of `guides-app/components/es-form/es-textfield`. Maybe something's getting fouled up there and interrupting it before it can populate the dropdown of the sidebar. It hits this once on the quick start page and sometimes more than once on each of the other pages I tried. And, yes, 'ToString' in the error has a capital T.

The other problem I noticed in passing. The examples with a header, like the HBS one on the Quick Start page, have the expected black background, but the plain examples, like the one with `cd ember-quickstart \n ember serve`, have no background, leaving strangely ghostly outline text. Comparing with more recent Edge, the `<pre>` tag in the old one has class `line-numbers` but no `language-bash`.

Hopefully, @sivakumar-kailasam, this will give you a head start. Many thanks!

**Comment by locks** [comment]
Howdy @lupestro! Sorry for the issue necromancy, but can you tell me if this is still an issue? Possibly the non-working versions have been dropping meanwhile? ;X

**Comment by locks** [comment]
Closing as stale. Let us know if it's still a concern @lupestro!
