### ISSUE TITLE
Consider changing the length of the `description` meta-data

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-source#494]
This is a continuation from a conversation I had with @sivakumar-kailasam in #135 

Currently, the description is limited to 260 characters because of a default in [ember-meta](https://github.com/shipshapecode/ember-meta) /cc @rwwagner90 

The main point of the conversation was this: 

> I remembered it was to a max limit around 300 ([moz.com/learn/seo/meta-description](https://moz.com/learn/seo/meta-description)).

**Comment by locks** [comment]
So, what's up with this my friends? 😁

**Comment by rwwagner90** [comment]
@locks I think it could be closed. I had read somewhere 260 was best. If there are new guidelines around that and 300 is better, please point me to those and we could update things.
