### ISSUE TITLE
404 error clicking on old-version-warning btn link on v1.10.0

### ISSUE THREAD

**Issue by shroy** [ember-learn/guides-source#495]
When navigating to [Views: Inserting Views in Templates v1.10.0](https://guides.emberjs.com/v1.10.0/views/inserting-views-in-templates/), the `VIEW v3.1.0` link returns a **404 error**. 

Error message in the response..

`
Error: Ember Data Request GET /content/v3.1.0/views/inserting-views-in-templates/index.json returned a 404
Payload (Empty Content-Type)
`

**Comment by MelSumner** [comment]
@anotheredward and @mansona let's figure out if there's a path forward for this- I verified tonight that the issue still exists. Thank you! 👍

**Comment by anotheredward** [comment]
Thanks for reminding me of this @MelSumner .
As far as I understand, we have two options:
1. Change the link button code to use the same logic as the version changer from my PR: #200 :
https://github.com/ember-learn/guides-app/pull/200 . This change is simple, and duplicates a bit of logic.

2. Move the logic I added up to where we handle 404s, that way we'll do a best guess no matter when the user comes from (eg: An old-link on a different site).
This change requires less duplication, and fixes a potential issue with external urls using the `release` version, but I am not sure what knock-on effects it might have.

Normally this wouldn't be a problem as a URL like:
https://guides.emberjs.com/v1.10.0/views/inserting-views-in-templates/
Should always be correct, that page will always exist for that specific version.

But the potentially problematic case is for external links is when a user uses the `release` version with a specific page:
https://guides.emberjs.com/release/views/inserting-views-in-templates/

Not sure if this is worth fixing, but it's worth being aware of :).

**Comment by mansona** [comment]
Hi @anotheredward 👋 sorry I didn't notice that you were linking to the guides-app repo before now 🙈 

The guides app repo no longer powers the templates for the ember guides, we are now using https://github.com/ember-learn/guidemaker-ember-template

I hope there hasn't been too much wasted effort 😫 this is entirely my fault for not updating the relevant contributing guides to point to the new place. Let me know if you need any help to get started with the new system, it should hopefully be a bit easier to work with than the old guides-app infrastructure

**Comment by anotheredward** [comment]
@mansona Thank you for your responses and for archiving the project to avoid future issues :).
There hasn't been much wasted effort, and I'll be glad to reflect the same changes in the newer repositories :).

**Comment by MinThaMie** [comment]
Will close this issue because it will be/has to be solved in https://github.com/ember-learn/guidemaker-ember-template/issues/17
