### ISSUE TITLE
Providing an offline experience

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/guides-source#496]
We could provide users with a button that could download content in the background & cache it via service workers so that they can read whatever version of docs they were viewing even when they go offline.

**Comment by mansona** [comment]
@locks why was this closed? I think it's something that we still want to pursue at some point in the future 🤔

**Comment by locks** [comment]
We do not have the bandwidth even in the case a contributor wants to follow up on this, so I think it's better to close it and whenever we want to pursue it again, we open a new issue with an up-to-date description.
The work is likely not going to be done in this repository as well, but at one of the underlying techs no?
