### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by rwwagner90** [ember-learn/guides-source#499]
The motivation for this change is best described by @acorncom: 

> The goal here is to dog food the approach, find snags early prior to it being common and help pave the path for the community. Because although not having jQuery in your app isn’t ever going to be required, it’s the type of thing that would be nice to first allow (and down the road might become the new default blueprint at some point in the future). Plus, we’ll want to point folks interested in doing this type of change toward learning team apps.

For more info see the conversation on #38

**Comment by locks** [comment]
What needs to happen to advance this?

**Comment by rwwagner90** [comment]
I'm not sure. I started opening PRs removing jQuery in all the things, when we initially were discussing this stuff, but I think we found we needed it for something, and the efforts fizzled out.

**Comment by locks** [comment]
I'm closing this for now as I think we've _mostly_ addressed it. We can open more specific issues for any remaining work!
