### ISSUE TITLE
Typo in guides-source/guides/v3.6.0/tutorial/service.md 

### ISSUE THREAD

**Issue by lisaychuang** [ember-learn/guides-source#506]
Hi learning team,

I'm working through the Tutorial right now, and noticed there's a typo:

> When the service calls `createMap` on our fake utility **`stubMapUtil`**, we will run asserts to validate that it is called. 

In the [code example](https://guides.emberjs.com/release/tutorial/service/), the unit test creates a variable `stubMapService` instead of `stubMapUtil`.

Please review if this is a typo, I think in past tutorials the test used `stubMapUtil`.

Thanks,
Lisa

**Comment by toddjordan** [comment]
Thanks for reporting!
