### ISSUE TITLE
Update how "JSON:API" is written

### ISSUE THREAD

**Issue by CodingItWrong** [ember-learn/guides-source#516]
A few months ago the JSON API spec standardized on writing the name of the spec "JSON:API". Here's the commit where they changed their own site to do so:

https://github.com/json-api/json-api/commit/5cead1156a67f7d4c45b6f2f3b9edaa67752c32d

I'd be happy to update all references to JSON API in the guides to the new "JSON:API" form—please give me a 👍 to confirm that'd be desired. Thanks!

**Comment by acorncom** [comment]
👍, seems good to me @CodingItWrong

**Comment by CodingItWrong** [comment]
Closed via #527
