### ISSUE TITLE
Standardize capitalization of "Ajax"

### ISSUE THREAD

**Issue by CodingItWrong** [ember-learn/guides-source#518]
In the "release" version of the guides, there seem to be three instances of "AJAX" in all-caps, and one instance of "Ajax" with only the first letter capitalized. We should make them consistent one way or the other.

Two arguments for "Ajax":
- Wikipedia lists both capitalizations but has "Ajax" as the first and one used throughout the article.
- A thread on the Drupal handbook discussed rationale for choosing "Ajax" - https://www.drupal.org/project/documentation/issues/356443

Whichever way we decide, I am happy to do a quick PR to update.

**Comment by acorncom** [comment]
I don't have strong preferences on this (@mansona / @jenweber / @locks do you?) , but per the MDN article on things (https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX) it uses Ajax throughout. Of interest is that their URL has `AJAX` in all caps ... 😉

**Comment by locks** [comment]
I'm fine with whichever!

**Comment by CodingItWrong** [comment]
K I'm gonna move forward with Ajax!

**Comment by MelSumner** [comment]
Thank you for doing this, @CodingItWrong 👍
