### ISSUE TITLE
Enhancement: Identify LTS versions

### ISSUE THREAD

**Issue by cah-danmonroe** [ember-learn/guides-source#531]
It is rather difficult to know which versions are marked LTS in the guides.  Can we make it easy to identify a version is marked LTS?  Perhaps add "LTS" in the version combo box?

**Comment by locks** [comment]
https://github.com/empress/guidemaker/pull/13
https://github.com/ember-learn/guidemaker-ember-template/pull/11
https://github.com/ember-learn/guides-source/pull/547
