### ISSUE TITLE
Guides should not use prototype extensions

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/guides-source#532]
The guides should not use prototype extensions. They cause a lot of problems in FastBoot environments, where objects cross realms.

## TODO
- [ ] Remove instances of using prototype extensions in the guides
- [ ] find appropriate place to use a note/callout (Zoey/Tomster says...) - "Prototype extensions can cause a lot of problems in FastBoot (link) environment, where objects cross realms."

**Comment by jenweber** [comment]
I searched the Guides and did not find any usages of `.on()`, `.observes()`, `.property()`. `camelize` and `underscore` are properly imported from Ember String, and there are no uses of `w()` (whatever that is), or any of the other convenience methods [here](https://api.emberjs.com/ember/release/classes/String).

In most cases, usages of `firstObject` are taught within the context of Ember Arrays, as a "special method."

This example in Enumerables is a problem:

```javascript
let animals = ['rooster', 'pig'];

animals.get('lastObject');
//=> "pig"

animals.pushObject('peacock');

animals.get('lastObject');
//=> "peacock"
```

**Comment by rwwagner90** [comment]
@jenweber another problem in enumerables:

```javascript
import EmberObject from '@ember/object';

let hawaii = EmberObject.create({
  capital: 'Honolulu'
});

let california = EmberObject.create({
  capital: 'Sacramento'
});

let states = [hawaii, california];

states.mapBy('capital');
//=> ["Honolulu", "Sacramento"]
```
