### ISSUE TITLE
ensure consistent code fencing label for JSON examples

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#565]
I propose we standardize `json` for [code fences](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) in JSON examples to preserve visual consistency.
Here we [use `json`](https://github.com/ember-learn/guides-source/blame/master/guides/release/models/customizing-serializers.md#L32). Here we [use `javascript`](https://github.com/ember-learn/guides-source/blame/master/guides/release/models/customizing-serializers.md#L296). Here we [use `text`](https://github.com/ember-learn/guides-source/blame/master/guides/release/models/finding-records.md#L75). I am not using blame because I am angry, just to show the *exact* line number.
Without unifying it, you can see the blocks highlighted differently in the guides:
# json 
<img width="828" alt="screen shot 2019-03-05 at 17 06 58" src="https://user-images.githubusercontent.com/472721/53840815-249e9780-3f69-11e9-980c-04cfce6c9e46.png">

# text
<img width="857" alt="screen shot 2019-03-05 at 17 06 26" src="https://user-images.githubusercontent.com/472721/53840816-249e9780-3f69-11e9-839d-8896b7d95e73.png">

**Comment by acorncom** [comment]
@efx this sounds great, would you have time to tackle it as well?

**Comment by efx** [comment]
@acorncom sure thing. I presume this should go into master?

**Comment by acorncom** [comment]
@efx sorry, this got lost in the notification flood on this end. Yep, `master` works well. If you **want** to go back and fix previous releases, that's fine as well, but we don't always do that
