### ISSUE TITLE
initializing object or array properties using init: do we still need this with native classes?

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#566]
In customizing [headers section](https://guides.emberjs.com/release/models/customizing-adapters/#toc_headers-customization), we state:
> Note that we set headers in init() because default property values should not be arrays or objects.

I think this prohibition is about [avoiding leaking state.](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/avoid-leaking-state-in-ember-objects.md#description)
Wouldn't using native classes supersede this implementation quirk? 
If so, what is the recommended way to set those properties?

**Comment by locks** [comment]
The two ways to initialize properties in native classes is in constructors or field initializers (`class A { propName = [1, 2, 3] }`).
However, since field initializers are still in stage 3 I would keep the `constructor` recommendation.

**Comment by efx** [comment]
@locks thanks for the explanation. I'm still unclear as the [migration guide](https://github.com/ember-learn/guides-source/blob/octane/guides/release/upgrading/editions.md#constructor-instead-of-init) recommendation says to use`constructor` and that field initializers are "completely ok".
Perhaps I'm not seeing something? As is there a policy for how we are teaching these concepts?
@pzuraq would you care to weigh in?

**Comment by pzuraq** [comment]
We should use class fields for this case, and stop teaching folks to initialize in `constructor`/`init` unless it's some fairly complicated initialization work.

As for `init` vs `constructor`, the gist is that if your parent class does not use `init` (or other EmberObject APIs), you're safe using `constructor`. Based on a quick look at the code for adapters/serializers/models, and our conversation with @runspired, I think it should be safe to use `constructor` in examples, but we should definitely prefer class fields.
