### ISSUE TITLE
proposal: refactor $.getJSON examples to use fetch

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#570]
Converting code examples for Octane has refreshed a discussion about using jQuery in trivial code examples. I think we should refactor code examples that feel dated due to using `$.getJSON`. See #33 for my prior hang ups. Tangential to https://github.com/ember-learn/guides-source/issues/499.
# current usage in release guides
* https://github.com/ember-learn/guides-source/blame/master/guides/release/models/index.md#L114
* https://github.com/ember-learn/guides-source/blame/master/guides/release/models/index.md#L143
* https://github.com/ember-learn/guides-source/blame/master/guides/release/models/finding-records.md#L93
* https://github.com/ember-learn/guides-source/blame/master/guides/release/routing/asynchronous-routing.md#L38

# why use window.fetch?
I propose we use [window.fetch](https://fetch.spec.whatwg.org/) for at least 3 reasons:
1. it is [widely supported](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility) by modern browsers.
2. In a land of jQuery free Ember applications, why should we promote depending on the entire jQuery library for a single function?
3. Easier teaching and mental model. By aligning with a web standard, we leverage existing teaching and developer experience. For new developers it gives them a helpful tool that could be considered a best practice in web development. Fetch's Promise based design flows nicely with concepts taught throughout the Ember guides and modern asynchronous web programming.

**Comment by acorncom** [comment]
@efx I like the idea here. Given that the browser matrix for Ember still includes IE 11, it seems like it would be best to be suggesting using https://github.com/ember-cli/ember-fetch so we don't deliberately steer folks toward something that could cause them headaches in production. Thoughts?

**Comment by efx** [comment]
@acorncom good point. I agree we should highlight that option with the reasoning for it so users can make informed decisions for their project.
