### ISSUE TITLE
[OCTANE] some code examples are not indented properly

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#601]
Notice how any JavaScript code example block in a list item has incorrect indentation:
<img width="1035" alt="Screen Shot 2019-03-14 at 11 21 02" src="https://user-images.githubusercontent.com/472721/54370067-60162180-464d-11e9-89ea-89aededb30e9.png">

https://github.com/ember-learn/guides-source/compare/octane...efx:fix-indent?expand=1

Simplified attempt to reproduce does not show the issue: https://jsfiddle.net/qkgoaufy/1/

**Comment by jenweber** [comment]
Closed by #668. Thank you for your help identifying this!
