### ISSUE TITLE
Set up robots.txt and GoogleAnalytics for the octane staging site

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#610]
We have some small adjustments to make to prepare for showing the Octane Guides in a separate staging app. This work should be done from the existing `octane` branch, and the PR should target `octane` and not master.

We need to adjust `public/robots.txt` to reflect the upcoming home of the Octane Guides staging, `octane-guides-preview.emberjs.com/release/`.

We also need to update Google Analytics hostname in the router: [Edit this line](https://github.com/ember-learn/guides-source/blob/master/app/router.js#L30) to be `octane-guides-preview.emberjs.com`

**Comment by jenweber** [comment]
Used [this resource](http://www.robotstxt.org/faq/prevent.html) to learn how to set robots.txt crawling to "disallow"

```
# http://www.robotstxt.org
User-agent: *
Disallow: /
```

**Comment by mansona** [comment]
This is done right? 🤔

**Comment by jenweber** [comment]
Closed by #627
