### ISSUE TITLE
[OCTANE] do some CSS hacks to hide the edit pencil and the search bar

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#611]
Do you like hacky quick fixes? Well, we have a job for you. Add some css that adds {display: none} for the edit pencil icon on every page of the guides, and also hides the search bar.

Why? We are deploying the Octane Guides Preview to a special staging app and neither of these things will work. It's important for UX.

This work should branch from the existing `octane` and make a PR back into `octane`. Thanks for your help!

**Comment by rwjblue** [comment]
Closed by #616
