### ISSUE TITLE
Refactor loading-and-error-substates to not use foo and bar

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#646]
We have so many good examples available to us that it doesn't make sense to use foo and bar here.

Read through `loading-and-error-substates.md` and see if you can improve it!

**Comment by acorncom** [comment]
The above is referencing https://guides.emberjs.com/release/routing/loading-and-error-substates/ (and the file that generates that page: https://github.com/ember-learn/guides-source/blob/master/guides/release/routing/loading-and-error-substates.md)

**Comment by Malolan-Balaji-T18128** [comment]
@jenweber can I have a go at this?

**Comment by uchihamalolan** [comment]
@jenweber can I have a go at this?

**Comment by glidej** [comment]
@jenweber It looks like this issue might be stale! #729 was merged back in April and appears to fix this issue.

**Comment by locks** [comment]
Closing this, thanks for the ping :)
