### ISSUE TITLE
Check for missing `{ action }` imports

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#654]
In the `octane` branch, we may have occasionally forgotten the following in code samples:

```javascript
import { action } from '@ember/object';
```

Search for `@action` throughout `guides/release` and see if it has an import with it in the code block. If it's missing, please add it. Make a PR back to `octane`.

**Comment by mike-north** [comment]
#656 has fixes for all occurrences of `@action` in the `guides/release/**/*.md`

**Comment by mike-north** [comment]
I think we can close this now

**Comment by locks** [comment]
Thanks for double checking!
