### ISSUE TITLE
How should we manage creating new version folders?

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#66]
**Current behavior:**
When we make a new folder of versions, we risk creating more work/losing valuable work when open PRs are still pointed at earlier versions. We also lose the git history.

**Desired behavior:**
We don't need to duplicate work when a new version is cut.

**Options:**
- merge or close PRs before making a new version
- make a "current" folder that holds the next version, and PRs always go there
- ???

**Comment by chrismou** [comment]
Personally I'd say the `current` directory makes more sense, as there'll always be times a PR isn't ready for the release and you don't want to be rushed into merging it to avoid work later.

As you say, if fixes all point at master, you only ever have to worry about backporting, and you can judge whether its worth it based on the importance.  Typos, for example, could probably just be left in most cases

**Comment by sivakumar-kailasam** [comment]
New features would need to be documented early in Dev cycle in the guides going forward since some of them require more time for review. Their content usually goes into n+2nd folder if 'n' is the current version of guides. This is an additional constraint to account for

**Comment by jenweber** [comment]
Closing, this has been less of a problem now that 3.x guides have stabilized.
