### ISSUE TITLE
Document Ember Guides publishing steps for new Ember releases

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#716]
3.9 is coming! What should a maintainer do once the blog post for that release is published?

> steps were cloning and renaming the release folder and updating the version.yml file
it handles the rest just like a website update (once CI tests pass, it can be merged, then is published automatically)

We should update MAINTAINERS.md

**Comment by villander** [comment]
@jenweber this can be closed

**Comment by jenweber** [comment]
Thanks!
