### ISSUE TITLE
Create redirects in Octane so legacy urls don't die

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#719]
In the Octane branch, we need to create redirects so that if someone visits a `release` url that doesn't exist anymore, they end up at the page that now handles that topic.

This can be done by creating folders and files that have the redirect, but not include those pages in `pages.yml`. See other version folders for how to do redirects.

You can see examples of redirects in https://github.com/ember-learn/guides-source/pull/297/files

**Comment by theroncross** [comment]
I'm interested in taking this on, but would like to clarify with an example before I get started.

Comparing the following:
https://guides.emberjs.com/release/getting-started/js-primer/
https://octane-guides-preview.emberjs.com/release/working-with-javascript/learning-javascript/

We need to add `guides/release/getting-started/js-primer.md` with the following
```
---
redirect: working-with-javascript/learning-javascript
---
```
Is that correct?

**Comment by llunn** [comment]
I believe the way theses redirects work is the source of #971

**Comment by MelSumner** [comment]
@theroncross yes that's correct

**Comment by theroncross** [comment]
Quick question - it looks like we still have `/templates/links`, but there isn't an entry for it in the table of contents widget on the left.

Intentional? Should I open an issue and PR to add it?

**Comment by locks** [comment]
@jenweber I believe you did a bunch of redirect work, do you remember if it addressed this issue?

**Comment by jenweber** [comment]
Yep, this was solved before launch!
