### ISSUE TITLE
on hold - consider showing `tracked` in classic components

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#720]
At the learning team meeting on 2019-04-04, and at an octane strike team meeting in early 2019, we discussed showing `tracked` in the Guides before the stable ship of Octane.

We will wait to make the changes that show tracked until it lands in stable Ember. This may be a moot point since MU is de-scoped from Octane and we're on the fast track to a stable release.

**Comment by locks** [comment]
Closing this until the discussion is revisited.
