### ISSUE TITLE
Label 3.8 as "LTS" in the Guides (one line change)

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#738]
This issue is great for a new contributor!

In the [latest release blog post](https://blog.emberjs.com/2019/04/10/ember-3-9-released.html), Ember version 3.8 was named an "LTS" or "Long Term Support" version, meaning that it will get bugfixes for longer than a regular release. We should show that clearly in the Guides!

Update the `ltsVersions` list in [`versions.yml`](https://github.com/ember-learn/guides-source/blob/master/versions.yml) to include 3.8. This will make it show up as LTS in this dropdown of the Guides:

![Screen Shot 2019-04-10 at 9 16 55 PM](https://user-images.githubusercontent.com/16627268/55923983-ff3f2200-5bd5-11e9-89da-d616cec1e7e4.png)

**Comment by BradLeftley** [comment]
@jenweber I can pick this up :)
