### ISSUE TITLE
Missing favicon for the Guides

### ISSUE THREAD

**Issue by saleswhale-vincent** [ember-learn/guides-source#764]
Per title, the Guides seem to be missing any kind of favicon. Unsure if this was a deliberate decision but I think having a favicon helps in scanning for the Guides tab in the browser, specially if I have multiple tabs open.

**Comment by jenweber** [comment]
If anyone wants to volunteer for this, it should be a quick fix!

You can get the favicon from [here](https://github.com/ember-learn/ember-website/blob/master/public/images/favicon.png) and I think link to it in index.html like in [this other repo](https://github.com/ember-learn/ember-website/blob/master/app/index.html). If that doesn't work for some reason, reach out to Chris Manson on Ember Discord (aka real_ate).
