### ISSUE TITLE
Strange artifact in Guides - Configuration - Handling Deprecations

### ISSUE THREAD

**Issue by greyhwndz** [ember-learn/guides-source#772]
Just noticed about the following strange thing that doesn't map out to the source in the repo.
@toddjordan could this be a rendering error that is browser based?
<img width="666" alt="Guides-Configuration-HandlingDeprecations-wt" src="https://user-images.githubusercontent.com/13173749/56859305-99b3a980-69bb-11e9-955f-2abef2cf6c0a.PNG">

**Comment by locks** [comment]
Fixed, thanks for the report.
