### ISSUE TITLE
Is the first unit tests example correct?

### ISSUE THREAD

**Issue by sarbbottam** [ember-learn/guides-source#774]
Hi there, thanks for maintaining and continuously improving `ember-learn` and ember guides. I am wondering if the below example is complete.

```
import { module, test } from 'qunit';

module('relativeDate', function(hooks) {
  test('format relative dates correctly', function(assert) {
    assert.equal(relativeDate('2018/01/28 22:24:30'), 'just now');
    assert.equal(relativeDate('2018/01/28 22:23:30'), '1 minute ago');
    assert.equal(relativeDate('2018/01/28 21:23:30'), '1 hour ago');
    assert.equal(relativeDate('2018/01/27 22:23:30'), 'Yesterday');
    assert.equal(relativeDate('2018/01/26 22:23:30'), '2 days ago');
  });
});
```

I cannot figure out how `relativeDate` function available in the above test code.
Should it have been statically `imported`  or `looked up` from the container?

Something like:

```js
import { relativeDate } from '<app-context>/utils/date-utils';
```

Best!

**Comment by locks** [comment]
You are correct, it should be imported. Would you be willing to send a PR to fix this?

**Comment by sarbbottam** [comment]
Sure, I could do that. Could you confirm if only `https://github.com/ember-learn/guides-source/blob/master/guides/release/testing/index.md` and it will cascade to all the other occurrences or all the [occurrences](https://github.com/ember-learn/guides-source/search?q=module%28%27relativeDate%27%2C+function%28hooks%29+%7B&unscoped_q=module%28%27relativeDate%27%2C+function%28hooks%29+%7B) need to be updated?

I could not find any related information the [CONTRIBUTING.md](https://github.com/ember-learn/guides-source/blob/master/CONTRIBUTING.md).
