### ISSUE TITLE
Super rentals link does not follow a11y recommendations

### ISSUE THREAD

**Issue by locks** [ember-learn/guides-source#784]
https://guides.emberjs.com/release/tutorial/routes-and-templates/#toc_adding-a-banner-with-navigation

```
    {{#link-to "index"}}
      <h1>
        <em>SuperRentals</em>
      </h1>
    {{/link-to}}
```

**Comment by toddjordan** [comment]
Will add it to https://github.com/ember-learn/super-rentals/pull/121
@locks Is there an ember link somewhere with the recommendation that we can include to reference in the text?

**Comment by toddjordan** [comment]
See also https://github.com/ember-learn/guides-source/issues/778
We should close this and add it as a step there.

**Comment by toddjordan** [comment]
Updated #778
