### ISSUE TITLE
Hidden jQuery dependency in Ember Superrentals

### ISSUE THREAD

**Issue by samuelherzog** [ember-learn/guides-source#789]
To approach Ember Octane, I reimplemented [`ember-superrentals` with the Octane blueprint](https://github.com/samuelherzog/octane-superrentals).
I learned the `ember-simple-leaflet-maps` extension relies on `ember-ajax`, which in turn relies on `@ember/jquery`. 

I think this is wrong, as jQuery is no longer a dependency for Ember Octane.

Originally I reported this in [`ember-ajax`](https://github.com/ember-cli/ember-ajax/issues/439), where @rwjblue asked me to create a tracking issue here.

There's also an [issue open for `ember-simple-leaflets`](https://github.com/ember-learn/ember-simple-leaflet-maps/issues/2).

**Comment by jenweber** [comment]
Hi @samuelherzog, this has been fixed now in v0.0.3 of the leaflets addon. Thanks for reporting!
