### ISSUE TITLE
invoking-actions-directly-on-component-collaborators bad example

### ISSUE THREAD

**Issue by mattmarcum** [ember-learn/guides-source#79]
https://guides.emberjs.com/release/components/triggering-changes-with-actions/#toc_invoking-actions-directly-on-component-collaborators

Hi hope this is the right place for this.  At the bottom of the section is a service `app/services/messaging.js` that has an `actions` hash with a method, `sendMessage` on it.  `sendMessage` should not be in an actions hash, it should just be directly accessible on the service itself.  I tried implementing this as is and it didn't work.  I moved my method out of the `actions` hash and it started working.

<img width="745" alt="screen shot 2018-06-05 at 5 50 44 pm" src="https://user-images.githubusercontent.com/4745044/41006903-02e18c4e-68e9-11e8-8f62-0efb3a839e1e.png">

**Comment by acorncom** [comment]
Thanks much @mattmarcum, any chance you'd be able to send in a PR to address the issue?

**Comment by mattmarcum** [comment]
https://ember-twiddle.com/3e57cb6d449c1e66ac758d721f3d0fe3
