### ISSUE TITLE
Unwanted trailing slashes on services page

### ISSUE THREAD

**Issue by rodrigoyoshida** [ember-learn/guides-source#83]
There are some unwanted trailing slashes on guides page causing errors when using that part of the code. Tried to paste it and confirmed that it does not work, also checked the official guides-source repository and the trailing slashes are not there. 

The trailing slashes come after the 'location' and 'element' words. 

```
getMapElement(location) {
    let camelizedLocation = camelize(location/); 
    let element = this.get(`cachedMaps.${camelizedLocation}`);
    if (!element/) {
      element = this.createMapElement();
      this.get('mapUtil').createMap(element, location/);
      this.set(`cachedMaps.${camelizedLocation}`, element/);
    }
    return element;
  },
```

Link: https://github.com/ember-learn/guides-source/blob/master/guides/v3.1.0/tutorial/service.md

**Comment by mansona** [comment]
hey @rodrigoyoshida thanks for the report 🎉 

Do you want to submit the PR for this yourself? The simplest way to do so is to click the pencil button at the top right of the page when you're looking at the production Guides but if you want to do any local development I'm happy to guide you through it 👍

**Comment by rodrigoyoshida** [comment]
Sure! Already did it. Changed the file and created a pull request.

**Comment by jenweber** [comment]
Closed by merging https://github.com/ember-learn/guides-source/pull/84

Thanks for your help with this!
