### ISSUE TITLE
Clicking on new version goes to 404

### ISSUE THREAD

**Issue by abdullah2891** [ember-learn/guides-source#843]
Steps to Reproduce:
1. Go to 
https://guides.emberjs.com/v1.10.0/testing/integration/
2. Click View "View v3.8.0" button
3. It goes to 404

**Comment by locks** [comment]
@shankarsridhar we have no reason to remove documentation for older versions

**Comment by llunn** [comment]
This appears to not longer result in a 404, with the View 3.11.0 link, nor using the dropdown to choose 3.8.0; in the former case it goes to the index page.
