### ISSUE TITLE
You attempted to override the "didTransition" method which is deprecated.

### ISSUE THREAD

**Issue by mdbiscan** [ember-learn/guides-source#844]
This method is being used in `router.js` and the logs are spitting out this error.

The guides do not show that `didTransition` is deprecated and it works as expected. Is this deprecation message viable? Will `didTransition` be deprecated?

**Comment by locks** [comment]
It is [definitely deprecated](https://deprecations.emberjs.com/v3.x#toc_deprecate-router-events)!
We are working on a fix https://github.com/ember-learn/guides-source/pull/839.
