### ISSUE TITLE
Create an Octane Upgrade strategy guide

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#849]
Yehuda and Vaidehi discovered that while they were upgrading the super rentals tutorial, they needed more instructions than just an explanation of new syntaxes. The strategy guide will help people get going in the right direction, even before reading all the possible docs.

**Comment by efx** [comment]
Would migrating away from dependency on `@ember/runloop` fit here? https://github.com/emberjs/ember.js/issues/17234 notes it as an action item, but I am unsure what this means for my application that depends on [runloop APIs](https://api.emberjs.com/ember/release/modules/@ember%2Frunloop).

**Comment by MelSumner** [comment]
@jenweber would this deck work? https://noti.st/melsumner/Hl16PZ/hands-on-with-ember-octane

**Comment by MelSumner** [comment]
This is in text format and is more guides friendly- https://www.notion.so/Atlas-Recommended-Migration-Order-a22f948a7cce4e01896d674f727bee74

**Comment by jenweber** [comment]
Closed, this has been deployed to the octane preview.
