### ISSUE TITLE
Ember JS Guides Tutorial Issue With Services Section - Wrong Command For Windows

### ISSUE THREAD

**Issue by gauravdasgupta** [ember-learn/guides-source#863]
Under the Services tutorial the instructions in the paragraph below won't work as shown in the code snippet for a Windows user.
Next, add your new API key to the application by stopping the server and restarting it with the environment variable, LEAFLET_MAPS_API_KEY

It Should be like - 
Note- If you are on Windows OS, then execute the below commands
set LEAFLET_MAPS_API_KEY=<your key here>
ember s

**Comment by locks** [comment]
Addressed in https://github.com/ember-learn/guides-source/pull/864 !
