### ISSUE TITLE
Adapter Docs have incorrect clippet

### ISSUE THREAD

**Issue by Benjy1979** [ember-learn/guides-source#871]
On 
https://guides.emberjs.com/v3.10.0/models/customizing-adapters/

It says that  "ember g adapter adapter-name"will give you 

```
import DS from 'ember-data';
export default DS.JSONAPIAdapter.extend({
  namespace: 'api/v1'
});
```

But when I try it it actually gives:
```
import ApplicationAdapter from './application';
export default ApplicationAdapter.extend({
});
```

**Comment by glidej** [comment]
@Benjy1979 👋I'm having trouble recreating this issue. When I run `ember g adapter adapter-name` on ember-cli v3.10.1 (which is what npm resolves when I `npm i ember-cli@3.10.0`) I get:

```
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
});
```

This still differs from the docs (`namespace` shouldn't be there), so there's definitely something going on here, but your output has a considerably more dramatic diff 😂. Can you confirm your `ember-cli` version so I can get a repro here and move forward with a fix?

**Comment by maxwondercorn** [comment]
This seem to be an issue in adapters.  I raised this issue https://github.com/emberjs/data/issues/7299 when I was updating the API documentation

**Comment by ijlee2** [comment]
Just going through the backlog. I think we can close this issue. Please create a new one when there can be a change to the Ember Guides?

Thanks,
