### ISSUE TITLE
Octane - link to the Octane-Classic Cheat sheet

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#877]
It's a WIP here https://github.com/jenweber/ember-octane-vs-classic-cheat-sheet

That work needs to be finished before we link to it

**Comment by maxwondercorn** [comment]
Is this the supposed to be the Syntax Conversion Guide shown on the Octane preview guides? I noticed the [link](https://guides.emberjs.com/release/reference/syntax-conversion-guide/) is broken and there isn't anything on syntax conversion in the guides source.

**Comment by MelSumner** [comment]
It should link here: https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/

**Comment by jenweber** [comment]
This cheat sheet is linked on the octane branch now, so this can be closed
