### ISSUE TITLE
built-in helpers page is missing some key helpers

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-learn/guides-source#881]
Page: https://guides.emberjs.com/release/templates/built-in-helpers/

List of builtin helpers: https://api.emberjs.com/ember/3.10/classes/Ember.Templates.helpers

I noticed this when I wanted to find a link to some good `hash` examples. 
Some of the other helpers would probably be good to document on the built-in-helpers page as well. 

I do see that there is this:
> For a full list of built-in Helpers, see the Ember.Templates.helpers API documentation.

so maybe, ... idk. maybe a list of what those are with links to the api documentation minimally? 🤷‍♂

**Comment by locks** [comment]
I think maybe we can even remove this guide and have an obvious link in the introduction of templates?

**Comment by MelSumner** [comment]
@NullVoxPopuli how does the indication to visit the API documentation for a full list not satisfy the issue?

@locks I don't think we should eliminate what's there but I think clarification could help.

**Comment by locks** [comment]
This page has changed, so I opened https://github.com/ember-learn/guides-source/issues/1418 for follow-up.
