### ISSUE TITLE
Dead Link at footer

### ISSUE THREAD

**Issue by kasinaat** [ember-learn/guides-source#91]
https://guides.emberjs.com/logos/

When I click the logos on the footer it leads to this page which displays nothing.

Edit:I noticed all the links in the footer displays nothing

**Comment by sivakumar-kailasam** [comment]
Are you sure about that url @
?

**Comment by kasinaat** [comment]
Yes I am sure

Hope this helps

![giterr](https://user-images.githubusercontent.com/21967976/41715164-31472b00-7570-11e8-8d24-2d5660855c95.PNG)

**Comment by sivakumar-kailasam** [comment]
oh I see what you mean. Thanks for reporting this.

**Comment by sivakumar-kailasam** [comment]
Fixed by https://github.com/ember-learn/ember-styleguide/pull/73

**Comment by kasinaat** [comment]
I think still the issue persists but you have closed it
