### ISSUE TITLE
Teach using attributes vs arguments on the binding-elements page

### ISSUE THREAD

**Issue by acorncom** [ember-learn/guides-source#911]
This section should be re-written. Specifically the guidance just below:

> To enable support for these attributes, an attribute binding must be added for each specific attribute on the component. To do this, you can extend the appropriate components...

Instead we should teach using attributes vs arguments.

_Originally posted by @rwjblue in https://github.com/ember-learn/guides-source/pull/837_

**Comment by locks** [comment]
This content is gone.
