### ISSUE TITLE
Can't run guides locally due to infinite render loop

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#914]
Contributors reported:

```
 TypeError: (0 , _algoliasearch.default) is not a function
```

and similar errors when they did not use the npm lockfile or tried to update dependencies. As of version 1.4 of `ember-auto-import`, polyfills are not included by default. This can be fixed by adding the following config to `ember-cli-build.js` in the upstream guidemaker:

```js
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    fingerprint: {
      extensions: ['js', 'css', 'map']
    },
    autoImport: {
      webpack: {
        node: {
          global: true
        }
      }
    }
  });
```

See https://github.com/ef4/ember-auto-import/pull/227

**Comment by jenweber** [comment]
Upstream PR https://github.com/ember-learn/guidemaker-ember-template/pull/23

When this is released, we should bump our template version

**Comment by mansona** [comment]
So as I mentioned in the "Upstream PR"... that won't actually change anything down here in guides-source 🤔 we need to add that autoImport config to this repo's ember-cli-build for it to do anything. 

We can do some magic in the index.js upstream but that is a bit strange messing with consuming apps config and I'm not too sure we should be relying on it too much.

**Comment by MelSumner** [comment]
@jenweber @mansona is this still an issue?

**Comment by glidej** [comment]
@MelSumner I'm running into this right now. If I change my package.json locally to reference [this](https://github.com/ember-learn/guidemaker-ember-template/pull/27) merge commit it works locally. 

```
"guidemaker-ember-template": "git+https://github.com/ember-learn/guidemaker-ember-template.git#8863b3df25f9b9425c2b33525273a74213b71db7",
```
