### ISSUE TITLE
Octane - upgrading guide uses html comments instead of hbs ones

### ISSUE THREAD

**Issue by efx** [ember-learn/guides-source#918]
I noticed that the [Editions Deep Dive](https://octane-guides-preview.emberjs.com/release/upgrading/editions/#toc_angle-bracket-syntax) page uses HTML comments for added explanation:
<img width="847" alt="Screen Shot 2019-07-08 at 14 24 23" src="https://user-images.githubusercontent.com/472721/60833396-2cc34980-a18c-11e9-80dd-01b77ee5b0d0.png">
The [no-html-comments](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-html-comments.md#no-html-comments) warns against usage.

I verified you see a warning when you create a new application and add HTML comments to a template. (I created one using the latest Octane blueprint: ` ember new my-app -b @ember/octane-app-blueprint`.)

1. do I have the correct understanding?
2. If I do not, this is a knowledge gap to be addressed somehow.

If so, fixing this issue requires auditing the octane branch of the guides for HTML comments and then migrating them to hbs comments.

**Comment by rwjblue** [comment]
Seems good to migrate them to handlebars comments to me.

**Comment by shankarsridhar** [comment]
Hello repo owners, I'll be happy to send a PR for this. Let me know 😃

**Comment by efx** [comment]
@shankarsridhar that would be great; go for it! You can open the PR against the Octane branch and if you hit any blockers asking in the #dev-ember-learning channel in discord is a good step.

**Comment by shankarsridhar** [comment]
I think this can be closed.
This was fixed by https://github.com/ember-learn/guides-source/pull/930

**Comment by locks** [comment]
Thanks!
