### ISSUE TITLE
Change "classic invocation" to "curly invocation" in angle bracket syntax conversion guide

### ISSUE THREAD

**Issue by rwjblue** [ember-learn/guides-source#929]
Currently the [angle bracket syntax conversion guide](https://guides.emberjs.com/release/reference/syntax-conversion-guide/#toc_angle-bracket-syntax) uses the term "classic invocation" to refer to curly invocation, unfortunately this conflicts pretty strongly with what we decided was "classic components".

Specifically, "classic components" means components extending from `Ember.Component`, it is pretty confusing to have "classic invocation" to use a different definition of "classic". For example, you can absolutely invoke `@glimmer/component` based components with curlies but they are _for sure_ not "classic components".

We should change usages of "classic" in the page I linked above to "curly" or "curlies" (based on usage).

**Comment by MelSumner** [comment]
Looks like this was resolved with #954
