### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by bekwam** [ember-learn/guides-source#936]
I'm going through the tutorial using 3.10.1.  The unit tests I generated don't quite match the guide.  For instance, the QUnit screenshot in "Testing Our Application As We Go" references 9 tests but my tutorial generated only 8.

**Comment by bekwam** [comment]
Here's my resulting QUnit report

![image](https://user-images.githubusercontent.com/6334243/61214448-edd64c00-a6d5-11e9-9993-a6fd1bc5050b.png)

**Comment by locks** [comment]
I believe we've since addressed this problem. Thanks for filing!
