### ISSUE TITLE
'role="button"' is missing

### ISSUE THREAD

**Issue by contrerasmarc** [ember-learn/guides-source#938]
in section 'Creating a Handlebars Helper':
In line 5 of the 4th 'black screen" I believe is missing ' role="button" ' (wrote in section 'Building a Simple Component')

**Comment by MelSumner** [comment]
Update https://guides.emberjs.com/release/tutorial/hbs-helper/ to use a `<button>` element instead of an `<a>` element: 
 
```hbs
<a
    onclick={{action 'toggleImageSize'}}
    class="image {{if this.isWide "wide"}}"
  >
    <img src={{this.rental.image}} alt="">
    <small>View Larger</small>
  </a>
```

**Comment by glidej** [comment]
@MelSumner I'd like to take a crack at this one. It looks like we'd need to update the usage in a few other files as well, [simple-component](https://github.com/ember-learn/guides-source/blob/master/guides/release/tutorial/simple-component.md), [service](https://github.com/ember-learn/guides-source/blob/master/guides/release/tutorial/service.md), [subroutes](https://github.com/ember-learn/guides-source/blob/master/guides/release/tutorial/subroutes.md) in addition to the original issue in [hbs-helper](https://github.com/ember-learn/guides-source/blob/master/guides/release/tutorial/hbs-helper.md). 

I'm not as familiar with this content as you are, does that look like an exhaustive list to you?

**Comment by MelSumner** [comment]
@glidej I think it's a great start, and if we find that we have missed anything more, we will already know how to improve it! :)

**Comment by locks** [comment]
This section is gone 😅
