### ISSUE TITLE
'     role="button">' must be deleted (with a '-' sign)

### ISSUE THREAD

**Issue by contrerasmarc** [ember-learn/guides-source#939]
In section 'Building a Simple Component': on the 8th black screen, I believe that line 3 must be deleted ('     role="button">')

**Comment by MelSumner** [comment]
This section: https://guides.emberjs.com/release/tutorial/simple-component/ 

- [ ] Should have instances of `<a role="button">` changed to be a button element. 
- [ ] confirm that the tests are not looking for that `<a>` element (update them if so)
- [ ] confirm that the styling is not dependent on the `<a>` element (update it to only depend on class names if so)

**Comment by locks** [comment]
I believe the section mentioned is gone!
