### ISSUE TITLE
Testing - Write a link checker that looks for 404s in API docs

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#953]
There are lots of links in the Guides! We need to know when the links to external resources like other website or the API docs are broken. Write a test that checks all API docs links for the release folder. We only want to check the release folder so we don't DDOS ourselves.

There are lots of open source libraries that can check links in markdown files. Pick one and see how it goes!

**Comment by sivakumar-kailasam** [comment]
One way to give this a try without worrying about launching a DDOS on us is to run a local instance of ember API docs in production mode and rewrite all the API urls you identify in your test code to check it against your local instance.

If you feel interested in this issue but need help getting started with this, feel free to reach out to me on discord

**Comment by llunn** [comment]
I'll take a stab at this one.

**Comment by jenweber** [comment]
Thank you @llunn! Let us know if you have any questions! Siva's idea makes a lot of sense to me. It's a bit tough to run the API docs 100% locally so please reach out if you hit any problems. The #dev-ember-learning channel on Discord is a good place to chat or bounce ideas.
