### ISSUE TITLE
Do we need the "Building For Production" section in the quick start guide?

### ISSUE THREAD

**Issue by chancancode** [ember-learn/guides-source#970]
The nature of the quick start guide is that it's _quick_, and it just walks you through the a few basic features to give you a taste test, omitting a lot of other equally useful things along the way. For example, it doesn't happen to teach you to add CSS, write a helper, or how to debug your app with Ember Inspector, and I think that's totally fine.

With that in mind, do we _really_ need to cover "building for production" in the quick start guide? I don't have any intrinsic reason to _not_ include it. However, the current section basically just covers two things:

1. Run `ember build -prod` to get a dist folder
2. Figure out how to deploy that

Specifically, this is all the content we have for the second part:

> The Ember community values collaboration and building common tools that everyone relies on. If you're interested in deploying your app to production in a fast and reliable way,
check out the [Ember CLI Deploy](http://ember-cli-deploy.com/) addon.
> 
> If you deploy your application to an Apache web server, first create a new virtual host for the application. To make sure all routes are handled by index.html, add the following directive to the application's virtual host configuration:
> 
> ```apacheconf
> FallbackResource index.html
> ```

Which feels very much like "How to draw an owl" to me:

![How to draw an owl](https://i.kym-cdn.com/photos/images/original/000/572/078/d6d.jpg)

For the intended audience, I don't think those few lines are helpful to anyone. If anything, they probably brings more questions than answers (this is the first time we mentioned "addon", and what even is an Apache web server?).

IMO, the quick start will be fine without the whole "production" section. Alternatively, if the goal is just that the reader have the option to show off their work on the public internet _somewhere_, we can be opinionated and just pick one relatively easy way to accomplish that (GitHub pages, Netlify, etc) and walk through the steps in more details.

**Comment by rwjblue** [comment]
I do think its vaguely important to make it clear that you should always be deploying production builds, but I totally agree that deployment concepts are quite a bit past "quick start".

**Comment by acorncom** [comment]
Agreed on the drawing an owl part (and choosing Apache vs any other approach is completely up for debate). That said, we've dealt with a number of folks over the years who had no idea that `ember-cli` built regular HTML, CSS and JS files that could be deployed anywhere, so whatever solution we take here should **probably** explain that part so that we don't end up with brand new folks who miss that concept completely

**Comment by chancancode** [comment]
What if we replace the last part of the quick start with a section called "Next Steps..." (or "Now What?", etc), where we have a few recommendations (links):

* Learn more about Ember (link to the rest of the guides)
* Deploying to the Internet (link to a detailed deployment guide)
* ...

**Comment by locks** [comment]
Addressing this is already planned when we do the move to tutorials.emberjs.com, and https://github.com/emberjs/rfcs/blob/master/text/0431-guides-restructure.md.
