### ISSUE TITLE
Broken (404) search link

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/guides-source#971]
![transpile](https://user-images.githubusercontent.com/1372946/62337851-24101b80-b48b-11e9-822f-6a57c8feab6d.gif)

* Search for "transpile"
* In lower left hand side, says link should be https://guides.emberjs.com/glossary/web-development#toc_transpile (doesn't go to this link, but is a 404)
* Goes to https://guides.emberjs.com/glossary#toc_transpile, link is a 404

I see the content here: https://github.com/ember-learn/guides-source/blob/6eb6fbd5933358d89c33a45e5619beee780acca2/guides/release/glossary/index.md

Don't know anything about the issue yet, but am game to help on this or other guides things! @ amyrlam on Discord

**Comment by theroncross** [comment]
Could be wrong, but I think these should go to `*/release/<route>` (e.g. https://guides.emberjs.com/release/glossary#toc_transpile)

**Comment by amyrlam** [comment]
Stale, closing
