### ISSUE TITLE
Octane - Rework templates section

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#973]
It is best for us to conceptualize templates as components. We should possibly integrate Components and Templates.

**Comment by chancancode** [comment]
yasss 🙌🏼 I was thinking the same thing as I was working on co-location updates. I thought that may be too big of a change, but if you think that’s a good idea also, maybe I can try to do some of this

**Comment by jenweber** [comment]
Closed, superseded by work being done in #1150
