### ISSUE TITLE
Apply prefer-const rule to MD files

### ISSUE THREAD

**Issue by francosioquim** [ember-learn/guides-source#989]
Some **.md** files with code previews are using `let variable` even though that variable never gets reassigned in the example. I think it's better to follow the rule on [prefer-const](https://eslint.org/docs/rules/prefer-const) but keen to hear your thoughts on this.

I can create a PR for this too.

**Comment by locks** [comment]
Thanks for your interest. For the Ember projects we use a strategy called [liberal let](https://madhatted.com/2016/1/25/let-it-be). Can you review that blog post and if there are `let` bindings that should be updated according to it?

**Comment by francosioquim** [comment]
👍 Cheers @locks for pointing that out.  That blog provides a good background on why **liberal let** makes sense to some degree.  I'm into **constantly const** but I don't want to turn this into a **liberal let** vs **constantly const** topic 😄 

The only main issue that I can think of is that more devs are following **constantly const** (I could be wrong?) especially on projects using *prefer-const* eslint rule.  This can be trivial and it all boils down to just simply replacing copy+paste and replace `let` with `const` .


#### [Writing Helpers](https://guides.emberjs.com/release/templates/writing-helpers/) Example: 
```
export function formatCurrency([value, ...rest]) {
  let dollars = Math.floor(value / 100);
  let cents = value % 100;
  let sign = '$';

  if (cents.toString().length === 1) { cents = '0' + cents; }
  return `${sign}${dollars}.${cents}`;
}
```
can be refactored to:
```
export function formatCurrency([value, ...rest]) {
  const dollars = Math.floor(value / 100);
  const sign = '$';
  let cents = value % 100;

  if (cents.toString().length === 1) { cents = '0' + cents; }
  return `${sign}${dollars}.${cents}`;
}
```

**Comment by MelSumner** [comment]
For me they are more indicators of intent- if I want to signal that something shouldn't  change, tI use `const`. If I want to signal that it's okay for it to change, then I use `let`. I thought this was standard usage. Is it not?

**Comment by rwjblue** [comment]
The guides should stick to our general project wide coding practices (coined "liberal let" in [this blog post](https://madhatted.com/2016/1/25/let-it-be)). We can decide to change that across all of our projects, but that is likely a topic for larger meta discussion (and not decided on here in the guides-source specifically).

**Comment by MelSumner** [comment]
Thank you for clarifying, @rwjblue! Closing this issue as a result of receiving this information.
