### ISSUE TITLE
Link to syntax conversion guide is broken

### ISSUE THREAD

**Issue by belgoros** [ember-learn/guides-source#995]
I tried to figure out how to convert my old-styled component syntax to the new one and discovered the [broken link](https://guides.emberjs.com/reference) in [components section](https://guides.emberjs.com/release/components/):
<img width="565" alt="Screenshot 2019-08-12 at 11 08 37" src="https://user-images.githubusercontent.com/83579/62855192-d51b7f00-bcf1-11e9-9803-b82f37472963.png">

that returns:
<img width="439" alt="Screenshot 2019-08-12 at 11 11 24" src="https://user-images.githubusercontent.com/83579/62855231-f67c6b00-bcf1-11e9-80a7-db441bf62503.png">

**Comment by mansona** [comment]
Hey @belgoros thanks for your issue report 👍 it was a known issue that has literally got fixed nearly the same moment that you reported the issue 😂 I think the deployment was still in progress at the time.

I have double-checked the live guides and it does look like the link is fixed now 🎉 thanks again for taking the time to report it!

**Comment by belgoros** [comment]
@mansona Ha-ha, cool, thank you. I'll try to be faster next time 😃
